<a href="https://colab.research.google.com/github/audreyakwenye/DS-Unit-2-Sprint-3-Advanced-Regression/blob/master/DS_Unit_2_Sprint_Challenge_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Unit 2 Sprint Challenge 3

## Logistic Regression and Beyond

In this sprint challenge you will fit a logistic regression modeling the probability of an adult having an income above 50K. The dataset is available at UCI:

https://archive.ics.uci.edu/ml/datasets/adult

Your goal is to:

1. Load, validate, and clean/prepare the data.
2. Fit a logistic regression model
3. Answer questions based on the results (as well as a few extra questions about the other modules)

Don't let the perfect be the enemy of the good! Manage your time, and make sure to get to all parts. If you get stuck wrestling with the data, simplify it (if necessary, drop features or rows) so you're able to move on. If you have time at the end, you can go back and try to fix/improve.

### Hints

It has a variety of features - some are continuous, but many are categorical. You may find [pandas.get_dummies](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html) (a method to one-hot encode) helpful!

The features have dramatically different ranges. You may find [sklearn.preprocessing.minmax_scale](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.minmax_scale.html#sklearn.preprocessing.minmax_scale) helpful!

In [0]:
import pandas as pd

In [24]:
df = pd.read_table('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', sep=',', header=None)

df[14].replace(' <=50K', 2,inplace=True)
df[14].replace(' >50K', 1,inplace=True)

df.head()


0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13  14  
0   United-States   2  
1   United-States   2  
2   United-States   2  
3   United-States   2  
4            Cuba   2

In [0]:
df.columns = ['age', 'emp_type', 'zip', 'edu', 'edu_years', 'status', 'job', 'family', 'race', 'gender', 'cap_gain', 'cap_loss', 'work_hours', 'country', 'salary']



## Part 1 - Load, validate, and prepare data

The data is available at: https://archive.ics.uci.edu/ml/datasets/adult

Load it, name the columns, and make sure that you've loaded the data successfully. Note that missing values for categorical variables can essentially be considered another category ("unknown"), and may not need to be dropped.

You should also prepare the data for logistic regression - one-hot encode categorical features as appropriate.

In [0]:
# TODO - your work!

## Part 2 - Fit and present a Logistic Regression

Your data should now be in a state to fit a logistic regression. Use scikit-learn, define your `X` (independent variable) and `y`, and fit a model.

Then, present results - display coefficients in as interpretible a way as you can (hint - scaling the numeric features will help, as it will at least make coefficients more comparable to each other). If you find it helpful for interpretation, you can also generate predictions for cases (like our 5 year old rich kid on the Titanic) or make visualizations - but the goal is your exploration to be able to answer the question, not any particular plot (i.e. don't worry about polishing it).

It is *optional* to use `train_test_split` or validate your model more generally - that is not the core focus for this week. So, it is suggested you focus on fitting a model first, and if you have time at the end you can do further validation.

In [100]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df['family'].replace(' Not-in-family', 1,inplace=True)
df['family'].replace(' Husband', 2,inplace=True)
df['family'].replace(' Own-child', 3,inplace=True)
df['family'].replace(' Unmarried', 4,inplace=True)
df['family'].replace(' Other-relative', 5,inplace=True)
df['family'].replace(' Wife', 6,inplace=True)


df['race'].replace(' White', 1,inplace=True)
df['race'].replace(' Black', 2,inplace=True)
df['race'].replace(' Asian-Pac-Islander', 3,inplace=True)
df['race'].replace(' Amer-Indian-Eskimo', 4,inplace=True)
df['race'].replace(' Other', 5,inplace=True)


df['gender'].replace(' Male', 1,inplace=True)
df['gender'].replace(' Female', 2,inplace=True)

LogisticRegression

sklearn.linear_model.logistic.LogisticRegression

In [112]:
X = df[['family']]
y = df.salary

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

adult_log = LogisticRegression().fit(X_train, y_train)
adult_log.score(X_train, y_train)
adult_log.predict(X_test)
family_coef = adult_log.coef_
print(family_coef)

test_case = np.array([[4]])
adult_log.predict_proba(test_case)[0]




[[0.02955265]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.23392624, 0.76607376])

array([[0.02955265]])

In [113]:
X = df[['race']]
y = df.salary

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

adult_log = LogisticRegression().fit(X_train, y_train)
adult_log.score(X_train, y_train)
adult_log.predict(X_test)
race_coef = adult_log.coef_
print(race_coef)

test_case = np.array([[4]])
adult_log.predict_proba(test_case)[0]



[[0.56933124]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.05485442, 0.94514558])

In [114]:
X = df[['gender']]
y = df.salary

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

adult_log = LogisticRegression().fit(X_train, y_train)
adult_log.score(X_train, y_train)
adult_log.predict(X_test)
gender_coef = adult_log.coef_
print(gender_coef)

test_case = np.array([[4]])
adult_log.predict_proba(test_case)[0]



[[1.26048582]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.00999694, 0.99000306])

## Part 3 - Analysis, Interpretation, and Questions

### Based on your above model, answer the following questions

1. What are 3 features positively correlated with income above 50k?
2. What are 3 features negatively correlated with income above 50k?
3. Overall, how well does the model explain the data and what insights do you derive from it?

*These answers count* - that is, make sure to spend some time on them, connecting to your analysis above. There is no single right answer, but as long as you support your reasoning with evidence you are on the right track.

Note - scikit-learn logistic regression does *not* automatically perform a hypothesis test on coefficients. That is OK - if you scale the data they are more comparable in weight.

### Match the following situation descriptions with the model most appropriate to addressing them

In addition to logistic regression, a number of other approaches were covered this week. Pair them with the situations they are most appropriate for, and briefly explain why.

Situations:
1. You are given data on academic performance of primary school students, and asked to fit a model to help predict "at-risk" students who are likely to receive the bottom tier of grades.
2. You are studying tech companies and their patterns in releasing new products, and would like to be able to model and predict when a new product is likely to be launched.
3. You are working on modeling expected plant size and yield with a laboratory that is able to capture fantastically detailed physical data about plants, but only of a few dozen plants at a time.

Approaches:
1. Ridge Regression
2. Quantile Regression
3. Survival Analysis

1. Race is highly corelated with making over 50k per year. 

2. Family status is not as correlated. 