In [27]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [28]:
# from kaggle.api.kaggle_api_extended import KaggleApi

# api = KaggleApi({"username":"dlromanoff","key":"3faca6957e86cee14fb3efd7b8168fa8"})
# api.athenticate()

%env KAGGLE_CONFIG_DIR=/Users/danielleromanoff/

# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

env: KAGGLE_CONFIG_DIR=/Users/danielleromanoff/
train.csv: Skipping, found more recently modified local copy (use --force to force download)
test.csv: Skipping, found more recently modified local copy (use --force to force download)
gender_submission.csv: Skipping, found more recently modified local copy (use --force to force download)


In [29]:
!wget https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
!unzip fma_metadata.zip

--2019-01-21 15:51:59--  https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
Resolving os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)... 2001:620:5ca1:2ff::ce53, 86.119.28.13
Connecting to os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)|2001:620:5ca1:2ff::ce53|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 358412441 (342M) [application/zip]
Saving to: ‘fma_metadata.zip.2’

fma_metadata.zip.2  100%[===================>] 341.81M  14.3MB/s    in 25s     

2019-01-21 15:52:25 (13.9 MB/s) - ‘fma_metadata.zip.2’ saved [358412441/358412441]

Archive:  fma_metadata.zip
   skipping: fma_metadata/README.txt  need PK compat. v4.6 (can do v4.5)
   skipping: fma_metadata/checksums  need PK compat. v4.6 (can do v4.5)
   skipping: fma_metadata/not_found.pickle  need PK compat. v4.6 (can do v4.5)
   skipping: fma_metadata/raw_genres.csv  need PK compat. v4.6 (can do v4.5)
   skipping: fma_metadata/raw_albums.csv  need PK compat. v4.6 (can do v4.5)
   skipping: fma_meta

In [30]:
train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550917

In [31]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [32]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [33]:
test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

In [34]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

/Users/danielleromanoff/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7103825136612022

In [35]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
log_reg.predict(test_case)[0]
# help(log_reg.predict)

1

In [37]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [38]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [39]:
log_reg.intercept_

array([1.45878264])

In [40]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
  return 1 / (1 + np.e**(-x))

In [41]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

In [64]:
tracks = pd.read_csv('tracks.csv')
tracks.head()

Unnamed: 0     album              album.1              album.2   album.3  \
0        NaN  comments         date_created        date_released  engineer   
1   track_id       NaN                  NaN                  NaN       NaN   
2          2         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
3          3         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
4          5         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   

     album.4 album.5      album.6  album.7   album.8 album.9  \
0  favorites      id  information  listens  producer    tags   
1        NaN     NaN          NaN      NaN       NaN     NaN   
2          4       1      <p></p>     6073       NaN      []   
3          4       1      <p></p>     6073       NaN      []   
4          4       1      <p></p>     6073       NaN      []   

               album.10 album.11 album.12               artist  \
0                 title   tracks     type    active_year_begin   
1                   NaN      NaN      NaN                  NaN   
2  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   
3  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   
4  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   

          artist.1           artist.2  \
0  active_year_end  associated_labels   
1              NaN                NaN   
2              NaN                NaN   
3              NaN                NaN   
4              NaN                NaN   

                                            artist.3  artist.4  \
0                                                bio  comments   
1                                                NaN       NaN   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0   
4  <p>A Way Of Life, A Collective of Hip-Hop from...         0   

              artist.5   artist.6 artist.7    artist.8    artist.9  \
0         date_created  favorites       id    latitude    location   
1                  NaN        NaN      NaN         NaN         NaN   
2  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   
3  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   
4  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   

     artist.10                                          artist.11 artist.12  \
0    longitude                                            members      name   
1          NaN                                                NaN       NaN   
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   

                                           artist.13 artist.14  \
0                                   related_projects      tags   
1                                                NaN       NaN   
2  The list of past projects is 2 long but every1...  ['awol']   
3  The list of past projects is 2 long but every1...  ['awol']   
4  The list of past projects is 2 long but every1...  ['awol']   

                                 artist.15       artist.16       set   set.1  \
0                                  website  wikipedia_page     split  subset   
1                                      NaN             NaN       NaN     NaN   
2  http://www.AzillionRecords.blogspot.com             NaN  training   small   
3  http://www.AzillionRecords.blogspot.com             NaN  training  medium   
4  http://www.AzillionRecords.blogspot.com             NaN  training   small   

      track   track.1   track.2              track.3              track.4  \
0  bit_rate  comments  composer         date_created        date_recorded   
1       NaN       NaN       NaN                  NaN                  NaN   
2    256000         0       NaN  2008-11-26 01:48:12  2008-11-26 00:00:00   
3    256000         0    

In [52]:
# tracks.describe()

In [65]:
tracks = tracks.drop(["Unnamed: 0"], axis=1)
tracks.columns = tracks.iloc[0]
tracks = tracks.drop([0, 1], axis = 0)
tracks.head()

0 comments         date_created        date_released engineer favorites id  \
2        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN         4  1   
3        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN         4  1   
4        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN         4  1   
5        0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN         4  6   
6        0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN         2  4   

0                                information listens producer tags  \
2                                    <p></p>    6073      NaN   []   
3                                    <p></p>    6073      NaN   []   
4                                    <p></p>    6073      NaN   []   
5                                        NaN   47632      NaN   []   
6  <p> "spiritual songs" from Nicky Cook</p>    2710      NaN   []   

0                 title tracks   type    active_year_begin  \
2  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
3  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
4  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
5     Constant Hitmaker      2  Album                  NaN   
6                 Niris     13  Album  1990-01-01 00:00:00   

0      active_year_end                                  associated_labels  \
2                  NaN                                                NaN   
3                  NaN                                                NaN   
4                  NaN                                                NaN   
5                  NaN  Mexican Summer, Richie Records, Woodsist, Skul...   
6  2011-01-01 00:00:00                                                NaN   

0                                                bio comments  \
2  <p>A Way Of Life, A Collective of Hip-Hop from...        0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...        0   
4  <p>A Way Of Life, A Collective of Hip-Hop from...        0   
5  <p><span style="font-family:Verdana, Geneva, A...        3   
6  <p>Songs written by: Nicky Cook</p>\n<p>VOCALS...        2   

0         date_created favorites id    latitude            location  \
2  2008-11-26 01:42:32         9  1  40.0583238          New Jersey   
3  2008-11-26 01:42:32         9  1  40.0583238          New Jersey   
4  2008-11-26 01:42:32         9  1  40.0583238          New Jersey   
5  2008-11-26 01:42:55        74  6         NaN                 NaN   
6  2008-11-26 01:42:52        10  4   51.895927  Colchester England   

0    longitude                                            members        name  \
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
5          NaN                           Kurt Vile, the Violators   Kurt Vile   
6     0.891874                                       Nicky Cook\n  Nicky Cook   

0                                   related_projects  \
2  The list of past projects is 2 long but every1...   
3  The list of past projects is 2 long but every1...   
4  The list of past projects is 2 long but every1...   
5                                                NaN   
6                                                NaN   

0                                               tags  \
2                                           ['awol']   
3                                           ['awol']   
4                                           ['awol']   
5                            ['philly', 'kurt vile']   
6  ['instrumentals', 'experimental pop', 'post pu...   

0                                  website wikipedia_page     split  subset  \
2  http://www.AzillionRecords.blogspot.com            NaN  training   small   
3  http://www.AzillionRecords.blogspot.com            NaN  training  medium   
4  http://www.AzillionRecords.blogspot.com            NaN 