<a href="https://colab.research.google.com/github/DimaKav/DS-Unit-2-Sprint-3-Advanced-Regression/blob/master/module1-logistic-regression/LS_DS_231_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

In [0]:
!pip install kaggle

In [0]:
# Note - you'll also have to sign up for Kaggle and authorize the API
# https://github.com/Kaggle/kaggle-api#api-credentials

# This essentially means uploading a kaggle.json file
# For Colab we can have it in Google Drive
from google.colab import drive
drive.mount('/content/drive')
%env KAGGLE_CONFIG_DIR=/content/drive/My Drive/

# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive
env: KAGGLE_CONFIG_DIR=/content/drive/My Drive/
  0% 0.00/59.8k [00:00<?, ?B/s]
100% 59.8k/59.8k [00:00<00:00, 23.7MB/s]
  0% 0.00/28.0k [00:00<?, ?B/s]
100% 28.0k/28.0k [00:00<00:00, 28.8MB/s]
  0% 0.00/3.18k [00:00<?, ?B/s]
100% 3.18k/3.18k [00:00<00:00, 2.15MB/s]


In [0]:
# How would we try to do this with linear regression?
import pandas as pd

train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

train_df.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [0]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [0]:
from sklearn.linear_model import LinearRegression

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550917

In [0]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [0]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [0]:
import numpy as np

test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

* The above prediction doesn't make intuitive sense. When we get to extremes in linear regression, our interpretation of coeffcicients doesn't make a lot of sense.
* The unbounded y-value in the calculation above is causing us some issues.

In [0]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7103825136612022

In [0]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
log_reg.predict(test_case)[0]

1

In [0]:
help(log_reg.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.logistic.LogisticRegression instance
    Predict class labels for samples in X.
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape [n_samples]
        Predicted class label per sample.



In [0]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [0]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [0]:
log_reg.intercept_

array([1.45878264])

In [0]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
  return 1 / (1 + np.e**(-x))

In [0]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

So, clearly a more appropriate model in this situation! For more on the math, [see this Wikipedia example](https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study).

For live - let's tackle [another classification dataset on absenteeism](http://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work) - it has 21 classes, but remember, scikit-learn LogisticRegression automatically handles more than two classes. How? By essentially treating each label as different (1) from some base class (0).

In [1]:
# Live - let's try absenteeism!
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/00445/Absenteeism_at_work_AAA.zip
!unzip Absenteeism_at_work_AAA.zip

--2019-02-25 18:23:07--  http://archive.ics.uci.edu/ml/machine-learning-databases/00445/Absenteeism_at_work_AAA.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66136 (65K) [application/zip]
Saving to: ‘Absenteeism_at_work_AAA.zip’

Absenteeism_at_work 100%[===================>]  64.59K   179KB/s    in 0.4s    

2019-02-25 18:23:07 (179 KB/s) - ‘Absenteeism_at_work_AAA.zip’ saved [66136/66136]

Archive:  Absenteeism_at_work_AAA.zip
  inflating: Absenteeism_at_work.arff  
  inflating: Absenteeism_at_work.csv  
  inflating: Absenteeism_at_work.xls  
  inflating: Attribute Information.docx  
  inflating: UCI_ABS_TEXT.docx       


In [0]:
import pandas as pd
df = pd.read_csv('Absenteeism_at_work.csv', sep=';')
pd.set_option('display.max_columns', 50)

In [7]:
df['Absenteeism time in hours'].value_counts()

8      208
2      157
3      112
1       88
4       60
0       44
16      19
24      16
40       7
5        7
32       6
64       3
80       3
120      3
112      2
56       2
48       1
7        1
104      1
Name: Absenteeism time in hours, dtype: int64

In [8]:
df.columns

Index(['ID', 'Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Transportation expense', 'Distance from Residence to Work',
       'Service time', 'Age', 'Work load Average/day ', 'Hit target',
       'Disciplinary failure', 'Education', 'Son', 'Social drinker',
       'Social smoker', 'Pet', 'Weight', 'Height', 'Body mass index',
       'Absenteeism time in hours'],
      dtype='object')

In [13]:
df.shape

(740, 21)

## Assignment - real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

In [14]:
!wget https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
!unzip fma_metadata.zip

--2019-02-25 19:07:07--  https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
Resolving os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)... 86.119.28.13, 2001:620:5ca1:2ff::ce53
Connecting to os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)|86.119.28.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 358412441 (342M) [application/zip]
Saving to: ‘fma_metadata.zip’

fma_metadata.zip    100%[===================>] 341.81M  24.9MB/s    in 15s     

2019-02-25 19:07:22 (23.3 MB/s) - ‘fma_metadata.zip’ saved [358412441/358412441]

Archive:  fma_metadata.zip
 bunzipping: fma_metadata/README.txt  
 bunzipping: fma_metadata/checksums  
 bunzipping: fma_metadata/not_found.pickle  
 bunzipping: fma_metadata/raw_genres.csv  
 bunzipping: fma_metadata/raw_albums.csv  
 bunzipping: fma_metadata/raw_artists.csv  
 bunzipping: fma_metadata/raw_tracks.csv  
 bunzipping: fma_metadata/tracks.csv  
 bunzipping: fma_metadata/genres.csv  
 bunzipping: fma_metadata/raw_echonest.cs

In [312]:
tracks = pd.read_csv('fma_metadata/tracks.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,5,6,8,12,18,20,21,22,24,33,34,38,39,44,47,49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
# tracks.set_option('display.max_columns', None)  # Unlimited columns

In [314]:
tracks.shape

(106576, 53)

# 1. Clean up the variable names

In [315]:
tracks.columns

Index(['Unnamed: 0', 'album', 'album.1', 'album.2', 'album.3', 'album.4',
       'album.5', 'album.6', 'album.7', 'album.8', 'album.9', 'album.10',
       'album.11', 'album.12', 'artist', 'artist.1', 'artist.2', 'artist.3',
       'artist.4', 'artist.5', 'artist.6', 'artist.7', 'artist.8', 'artist.9',
       'artist.10', 'artist.11', 'artist.12', 'artist.13', 'artist.14',
       'artist.15', 'artist.16', 'set', 'set.1', 'track', 'track.1', 'track.2',
       'track.3', 'track.4', 'track.5', 'track.6', 'track.7', 'track.8',
       'track.9', 'track.10', 'track.11', 'track.12', 'track.13', 'track.14',
       'track.15', 'track.16', 'track.17', 'track.18', 'track.19'],
      dtype='object')

In [316]:
tracks = pd.read_csv('fma_metadata/tracks.csv', header=1)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [317]:
tracks.head()

Unnamed: 0  comments         date_created        date_released engineer  \
0   track_id       NaN                  NaN                  NaN      NaN   
1          2       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
2          3       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3          5       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4         10       0.0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   

   favorites   id information  listens producer tags                 title  \
0        NaN  NaN         NaN      NaN      NaN  NaN                   NaN   
1        4.0  1.0     <p></p>   6073.0      NaN   []  AWOL - A Way Of Life   
2        4.0  1.0     <p></p>   6073.0      NaN   []  AWOL - A Way Of Life   
3        4.0  1.0     <p></p>   6073.0      NaN   []  AWOL - A Way Of Life   
4        4.0  6.0         NaN  47632.0      NaN   []     Constant Hitmaker   

   tracks   type    active_year_begin active_year_end  \
0     NaN    NaN                  NaN             NaN   
1     7.0  Album  2006-01-01 00:00:00             NaN   
2     7.0  Album  2006-01-01 00:00:00             NaN   
3     7.0  Album  2006-01-01 00:00:00             NaN   
4     2.0  Album                  NaN             NaN   

                                   associated_labels  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4  Mexican Summer, Richie Records, Woodsist, Skul...   

                                                 bio  comments.1  \
0                                                NaN         NaN   
1  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
4  <p><span style="font-family:Verdana, Geneva, A...         3.0   

        date_created.1  favorites.1  id.1   latitude    location  longitude  \
0                  NaN          NaN   NaN        NaN         NaN        NaN   
1  2008-11-26 01:42:32          9.0   1.0  40.058324  New Jersey -74.405661   
2  2008-11-26 01:42:32          9.0   1.0  40.058324  New Jersey -74.405661   
3  2008-11-26 01:42:32          9.0   1.0  40.058324  New Jersey -74.405661   
4  2008-11-26 01:42:55         74.0   6.0        NaN         NaN        NaN   

                                             members       name  \
0                                                NaN        NaN   
1  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
2  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
3  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
4                           Kurt Vile, the Violators  Kurt Vile   

                                    related_projects                   tags.1  \
0                                                NaN                      NaN   
1  The list of past projects is 2 long but every1...                 ['awol']   
2  The list of past projects is 2 long but every1...                 ['awol']   
3  The list of past projects is 2 long but every1...                 ['awol']   
4                                                NaN  ['philly', 'kurt vile']   

                                   website wikipedia_page     split  subset  \
0                                      NaN            NaN       NaN     NaN   
1  http://www.AzillionRecords.blogspot.com            NaN  training   small   
2  http://www.AzillionRecords.blogspot.com            NaN  training  medium   
3  http://www.AzillionRecords.blogspot.com            NaN  training   small   
4                      http://kurtvile.com            NaN  training   small   

   bit_rate  comments.2   composer       date_created.2        date_recorded  \
0       NaN         NaN        NaN                  NaN      

In [0]:
tracks.rename(columns={'Unnamed: 0':'track_id'}, inplace=True)
tracks.drop(0, axis=0, inplace=True)

In [319]:
tracks.sample(5)

track_id  comments         date_created        date_released engineer  \
70973   107963       0.0  2014-08-03 12:03:54  2014-07-05 00:00:00      NaN   
73964   111909       0.0  2014-12-08 22:50:52  1999-12-14 00:00:00      NaN   
59665    87468       0.0  2013-07-24 10:35:18                  NaN      NaN   
89196   131603       0.0  2016-01-30 16:13:51  2016-01-31 00:00:00      NaN   
39335    58927       0.0  2012-01-11 17:27:48  2010-01-01 00:00:00      NaN   

       favorites       id                                        information  \
70973        1.0  16800.0                                                NaN   
73964        1.0  17277.0  <p><span style="color:#333333;font-family:'Dro...   
59665        1.0  14730.0                                                NaN   
89196        1.0  19825.0                                                NaN   
39335        2.0  10831.0  <p>Individual Chorale Preludes from the comple...   

       listens producer                                               tags  \
70973  63916.0      NaN                                                 []   
73964  13332.0      NaN  ['camden', 'dream pop', 'rew', 'milwaukee', 'd...   
59665  16354.0      NaN                                                 []   
89196   4427.0      NaN  ['post rock', 'soundtrack', 'experimental comp...   
39335   9527.0      NaN                                                 []   

                                                   title  tracks   type  \
70973                                      Passe​-​temps    10.0  Album   
73964                                   Reel Time Canvas    10.0  Album   
59665                                       a nos amours     6.0  Album   
89196  Stochastic Deployment vol1: Awakening of the S...    28.0  Album   
39335      Bach Organ Works: Individual Chorale Preludes    63.0  Album   

         active_year_begin      active_year_end associated_labels  \
70973                  NaN                  NaN               NaN   
73964  1998-01-01 00:00:00  2000-01-01 00:00:00               NaN   
59665                  NaN                  NaN               NaN   
89196                  NaN                  NaN               NaN   
39335                  NaN                  NaN               NaN   

                                                     bio  comments.1  \
70973                                                NaN         0.0   
73964  <p><span style="font-size:16pt;font-family:Tim...         1.0   
59665                                                NaN         0.0   
89196                                                NaN         0.0   
39335  <p>James Kibbie is Professor of Organ at the U...         0.0   

            date_created.1  favorites.1     id.1   latitude         location  \
70973  2014-08-03 12:03:07         15.0  18812.0        NaN  Rabat (Morocco)   
73964  2014-12-08 22:46:00          2.0  19198.0        NaN        Milwaukee   
59665  2013-04-29 19:30:39          0.0  16197.0        NaN              NaN   
89196  2015-03-17 16:46:02          5.0  19815.0        NaN              NaN   
39335  2012-01-11 14:18:44         14.0  12750.0  42.281875    Ann Arbor, MI   

       longitude                                            members  \
70973        NaN                                                NaN   
73964        NaN  Eric Osterman\nWilliam J Seidel\nRyan E Weber\...   
59665        NaN                                                NaN   
89196        NaN                                                NaN   
39335 -83.748479                                                NaN   

               name related_projects  \
70973       Winston              NaN   
73964        Camden              NaN   
59665      Colombey              NaN   
89196        SULCUS              NaN   
39335  James Kibbie              NaN   

                                                  tags.1  \
70973                                        ['winston']   
73964        

In [320]:
tracks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 106574 entries, 1 to 106574
Data columns (total 53 columns):
track_id             106574 non-null object
comments             106574 non-null float64
date_created         103045 non-null object
date_released        70294 non-null object
engineer             15295 non-null object
favorites            106574 non-null float64
id                   106574 non-null float64
information          83149 non-null object
listens              106574 non-null float64
producer             18060 non-null object
tags                 106574 non-null object
title                105549 non-null object
tracks               106574 non-null float64
type                 100066 non-null object
active_year_begin    22711 non-null object
active_year_end      5375 non-null object
associated_labels    14271 non-null object
bio                  71156 non-null object
comments.1           106574 non-null float64
date_created.1       105718 non-null object
favorites.1 

In [321]:
tracks.columns

Index(['track_id', 'comments', 'date_created', 'date_released', 'engineer',
       'favorites', 'id', 'information', 'listens', 'producer', 'tags',
       'title', 'tracks', 'type', 'active_year_begin', 'active_year_end',
       'associated_labels', 'bio', 'comments.1', 'date_created.1',
       'favorites.1', 'id.1', 'latitude', 'location', 'longitude', 'members',
       'name', 'related_projects', 'tags.1', 'website', 'wikipedia_page',
       'split', 'subset', 'bit_rate', 'comments.2', 'composer',
       'date_created.2', 'date_recorded', 'duration', 'favorites.2',
       'genre_top', 'genres', 'genres_all', 'information.1', 'interest',
       'language_code', 'license', 'listens.1', 'lyricist', 'number',
       'publisher', 'tags.2', 'title.1'],
      dtype='object')

In [322]:
tracks['genre_top'].value_counts()

Rock                   14182
Experimental           10608
Electronic              9372
Hip-Hop                 3552
Folk                    2803
Pop                     2332
Instrumental            2079
International           1389
Classical               1230
Jazz                     571
Old-Time / Historic      554
Spoken                   423
Country                  194
Soul-RnB                 175
Blues                    110
Easy Listening            24
Name: genre_top, dtype: int64

In [323]:
tracks.isna().sum()

track_id                  0
comments                  0
date_created           3529
date_released         36280
engineer              91279
favorites                 0
id                        0
information           23425
listens                   0
producer              88514
tags                      0
title                  1025
tracks                    0
type                   6508
active_year_begin     83863
active_year_end      101199
associated_labels     92303
bio                   35418
comments.1                0
date_created.1          856
favorites.1               0
id.1                      0
latitude              62030
location              36364
longitude             62030
members               59725
name                      0
related_projects      93422
tags.1                    0
website               27318
wikipedia_page       100993
split                     0
subset                    0
bit_rate                  0
comments.2                0
composer            

In [0]:
tracks.drop(['publisher','lyricist','language_code','information.1','date_recorded',
             'composer','wikipedia_page','engineer','active_year_begin',
             'active_year_end','associated_labels','producer'],axis=1,inplace=True)

In [0]:
tracks.drop(['latitude','location','longitude','members','date_released'],
             axis=1,inplace=True)

In [0]:
tracks.drop('related_projects',axis=1,inplace=True)

In [0]:
tracks.drop('information',axis=1,inplace=True)

In [0]:
tracks.drop(['bio','website','license','date_created.1','type','date_created'],axis=1,inplace=True)

Go through each one and see if they're relevant by sampling each column

In [329]:
tracks.isna().sum()

track_id              0
comments              0
favorites             0
id                    0
listens               0
tags                  0
title              1025
tracks                0
comments.1            0
favorites.1           0
id.1                  0
name                  0
tags.1                0
split                 0
subset                0
bit_rate              0
comments.2            0
date_created.2        0
duration              0
favorites.2           0
genre_top         56976
genres                0
genres_all            0
interest              0
listens.1             0
number                0
tags.2                0
title.1               1
dtype: int64

In [0]:
tracks.dropna(subset=['title'],inplace=True)

In [349]:
tracks['title'].isna().sum()

0

I think we can predict genres on the the labels that we have and then predict them for the one that are missing.

# 2. Logistic regression on numeric columns
We'll only factorize genre_top for now

Let's train on whatever genres we have and test on the ones we don't

In [352]:
tracks[tracks.isnull().any(axis=1)].shape, tracks.dropna().shape

((56261, 28), (49288, 28))

In [0]:
# Train with top_genres missing
df_train = tracks[tracks.isnull().any(axis=1)]
# Test with genres present
df_test = tracks.dropna()

In [0]:
# Create new dataframe no missing genres_top
df = df_test

In [0]:
# Factorize the objects
char_cols = df.dtypes.pipe(lambda x: x[x == 'object']).index

for c in char_cols:
    df[c] = pd.factorize(df[c])[0]

In [376]:
df['genre_top'].value_counts()

2     14155
3     10544
6      9259
0      3536
4      2773
1      2325
14     2070
8      1378
12     1212
5       564
13      553
7       421
11      194
9       175
10      105
15       24
Name: genre_top, dtype: int64

In [381]:
from sklearn import metrics
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Create features matrix
features = df.loc[:,df.columns != 'genre_top']

# Create target vector
target = df['genre_top']

# Create standardizer
standardizer = StandardScaler()

# Create logistic regression object
logit = LogisticRegression()

# Create a pipeline that standardizes, then runs logistic regression
pipeline = make_pipeline(standardizer, logit)

# Create k-Fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=1)

# Conduct k-fold cross-validation
cv_results = cross_val_score(pipeline, # Pipeline
                             features, # Feature matrix
                             target, # Target vector
                             cv=kf, # Cross-validation technique
                             scoring="accuracy", # Loss function
                             n_jobs=-1) # Use all CPU scores

# Calculate mean
cv_results.mean()

0.43241809259669123

### Different Approach:

In [385]:
X = df.loc[:,df.columns != 'genre_top']
y = df['genre_top']

model = LogisticRegression(random_state=42, solver='lbfgs', multi_class='multinomial', max_iter=100)
model.fit(X,y)
model.score(X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.34247687063788346

In [386]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

model2 = LogisticRegression(random_state=42, multi_class='multinomial', solver='lbfgs', max_iter=100)
model2.fit(X_train,y_train)
model2.score(X_test,y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.34418113942541795

This is the biggest data you've played with so far, and while it does generally fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

## Resources and stretch goals

- Check out the other .csv files from the FMA dataset, and see if you can join them or otherwise fit interesting models with them
- [Logistic regression from scratch in numpy](https://blog.goodaudience.com/logistic-regression-from-scratch-in-numpy-5841c09e425f) - if you want to dig in a bit more to both the code and math (also takes a gradient descent approach, introducing the logistic loss function)
- Create a visualization to show predictions of your model - ideally show a confidence interval based on error!
- Check out and compare classification models from scikit-learn, such as [SVM](https://scikit-learn.org/stable/modules/svm.html#classification), [decision trees](https://scikit-learn.org/stable/modules/tree.html#classification), and [naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html). The underlying math will vary significantly, but the API (how you write the code) and interpretation will actually be fairly similar.
- Sign up for [Kaggle](https://kaggle.com), and find a competition to try logistic regression with
- (Not logistic regression related) If you enjoyed the assignment, you may want to read up on [music informatics](https://en.wikipedia.org/wiki/Music_informatics), which is how those audio features were actually calculated. The FMA includes the actual raw audio, so (while this is more of a longterm project than a stretch goal, and won't fit in Colab) if you'd like you can check those out and see what sort of deeper analysis you can do.