<a href="https://colab.research.google.com/github/donw385/DS-Unit-2-Sprint-3-Advanced-Regression/blob/master/module1-logistic-regression/LS_DS_231_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

In [0]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np


In [3]:
!pip install kaggle

In [6]:
# Note - you'll also have to sign up for Kaggle and authorize the API
# https://github.com/Kaggle/kaggle-api#api-credentials

# This essentially means uploading a kaggle.json file
# For Colab we can have it in Google Drive
from google.colab import drive
drive.mount("/content/drive", force_remount=True)
%env KAGGLE_CONFIG_DIR=/content/drive/My Drive/

# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

Mounted at /content/drive
env: KAGGLE_CONFIG_DIR=/content/drive/My Drive/
401 - Unauthorized


In [0]:
# How would we try to do this with linear regression?

train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

train_df.head()

FileNotFoundError: ignored

In [0]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [0]:

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550917

In [0]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [0]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [0]:
import numpy as np

test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

In [0]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7103825136612022

In [0]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
log_reg.predict(test_case)[0]

1

In [0]:
help(log_reg.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.logistic.LogisticRegression instance
    Predict class labels for samples in X.
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape [n_samples]
        Predicted class label per sample.



In [0]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [0]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [0]:
log_reg.intercept_

array([1.45878264])

In [0]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
  return 1 / (1 + np.e**(-x))

In [0]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

So, clearly a more appropriate model in this situation! For more on the math, [see this Wikipedia example](https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study).

For live - let's tackle [another classification dataset on absenteeism](http://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work) - it has 21 classes, but remember, scikit-learn LogisticRegression automatically handles more than two classes. How? By essentially treating each label as different (1) from some base class (0).

In [0]:
pd.set_option('display.max_columns', 50)

In [7]:
# Live - let's try absenteeism!

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00445/Absenteeism_at_work_AAA.zip
  
  

--2019-02-25 18:18:35--  https://archive.ics.uci.edu/ml/machine-learning-databases/00445/Absenteeism_at_work_AAA.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66136 (65K) [application/zip]
Saving to: ‘Absenteeism_at_work_AAA.zip’

Absenteeism_at_work 100%[===================>]  64.59K  --.-KB/s    in 0.09s   

2019-02-25 18:18:36 (730 KB/s) - ‘Absenteeism_at_work_AAA.zip’ saved [66136/66136]



In [8]:
!unzip Absenteeism_at_work_AAA.zip

Archive:  Absenteeism_at_work_AAA.zip
  inflating: Absenteeism_at_work.arff  
  inflating: Absenteeism_at_work.csv  
  inflating: Absenteeism_at_work.xls  
  inflating: Attribute Information.docx  
  inflating: UCI_ABS_TEXT.docx       


In [11]:
!head Absenteeism_at_work.csv

ID;Reason for absence;Month of absence;Day of the week;Seasons;Transportation expense;Distance from Residence to Work;Service time;Age;Work load Average/day ;Hit target;Disciplinary failure;Education;Son;Social drinker;Social smoker;Pet;Weight;Height;Body mass index;Absenteeism time in hours
11;26;7;3;1;289;36;13;33;239.554;97;0;1;2;1;0;1;90;172;30;4
36;0;7;3;1;118;13;18;50;239.554;97;1;1;1;1;0;0;98;178;31;0
3;23;7;4;1;179;51;18;38;239.554;97;0;1;0;1;0;0;89;170;31;2
7;7;7;5;1;279;5;14;39;239.554;97;0;1;2;1;1;0;68;168;24;4
11;23;7;5;1;289;36;13;33;239.554;97;0;1;2;1;0;1;90;172;30;2
3;23;7;6;1;179;51;18;38;239.554;97;0;1;0;1;0;0;89;170;31;2
10;22;7;6;1;361;52;3;28;239.554;97;0;1;1;1;0;4;80;172;27;8
20;23;7;6;1;260;50;11;36;239.554;97;0;1;4;1;0;0;65;168;23;4
14;19;7;2;1;155;12;14;34;239.554;97;0;1;2;1;0;0;95;196;25;40


In [17]:
df = pd.read_csv('Absenteeism_at_work.csv', sep =';')
df.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   Hit target  Disciplinary failure  Education  Son  \
0                 239.554          97                     0          1    2   
1                 239.554          97                     1          1    1   
2                 239.554          97                     0          1    0   
3                 239.554          97                     0          1    2   
4                 239.554          97                     0          1    2   

   Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0               1              0    1      90     172               30   
1               1              0    0      98     178               31   
2               1              0    0      89     170               31   
3               1              1    0      68     168               24   
4               1              0    1      90     172               30   

   Absenteeism time in hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [19]:
df['Disciplinary failure'].value_counts()

0    700
1     40
Name: Disciplinary failure, dtype: int64

In [20]:
df['Reason for absence'].value_counts()

23    149
28    112
27     69
13     55
0      43
19     40
22     38
26     33
25     31
11     26
10     25
18     21
14     19
1      16
7      15
6       8
12      8
8       6
21      6
9       4
5       3
24      3
16      3
4       2
15      2
3       1
2       1
17      1
Name: Reason for absence, dtype: int64

In [21]:
df.columns

Index(['ID', 'Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Transportation expense', 'Distance from Residence to Work',
       'Service time', 'Age', 'Work load Average/day ', 'Hit target',
       'Disciplinary failure', 'Education', 'Son', 'Social drinker',
       'Social smoker', 'Pet', 'Weight', 'Height', 'Body mass index',
       'Absenteeism time in hours'],
      dtype='object')

In [0]:
X = df.drop(['ID', 'Reason for absence'],axis=1)
y = df['Reason for absence']

In [26]:
#half the categories are right

model = LogisticRegression(random_state=42)
model.fit(X,y)
model.score(X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.49864864864864866

In [27]:
model = LogisticRegression(random_state=42, solver ='lbfgs',multi_class='multinomial',max_iter=10000)
model.fit(X,y)
model.score(X,y)

0.5121621621621621

In [0]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y, test_size=.5,random_state=42)

In [31]:
model2 = LogisticRegression(random_state=42, solver ='lbfgs',multi_class='multinomial',max_iter=8000)
model2.fit(X_train,Y_train)
model2.score(X_test,Y_test)

0.3783783783783784

## Assignment - real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

In [32]:
!wget https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
!unzip fma_metadata.zip

--2019-02-25 19:06:17--  https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
Resolving os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)... 86.119.28.13, 2001:620:5ca1:2ff::ce53
Connecting to os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)|86.119.28.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 358412441 (342M) [application/zip]
Saving to: ‘fma_metadata.zip’

fma_metadata.zip    100%[===================>] 341.81M  17.6MB/s    in 33s     

2019-02-25 19:06:51 (10.4 MB/s) - ‘fma_metadata.zip’ saved [358412441/358412441]

Archive:  fma_metadata.zip
 bunzipping: fma_metadata/README.txt  
 bunzipping: fma_metadata/checksums  
 bunzipping: fma_metadata/not_found.pickle  
 bunzipping: fma_metadata/raw_genres.csv  
 bunzipping: fma_metadata/raw_albums.csv  
 bunzipping: fma_metadata/raw_artists.csv  
 bunzipping: fma_metadata/raw_tracks.csv  
 bunzipping: fma_metadata/tracks.csv  
 bunzipping: fma_metadata/genres.csv  
 bunzipping: fma_metadata/raw_echonest.cs

In [79]:
tracks = pd.read_csv('fma_metadata/tracks.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,5,6,8,12,18,20,21,22,24,33,34,38,39,44,47,49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [34]:
tracks.describe()

Unnamed: 0   album              album.1              album.2  \
count      106575  106575               103046                70295   
unique     106575      29                14341                 3670   
top         21715       0  2015-01-26 13:04:57  2008-01-01 00:00:00   
freq            1   71187                  310                  667   

               album.3  album.4  album.5  \
count            15296   106575   106575   
unique             623       65    14929   
top     Ernie Indradat        0       -1   
freq               876    45753      805   

                                                  album.6  album.7  \
count                                               83150   106575   
unique                                              11076    11351   
top     <p class="p1" style="margin: 0px; padding: 8px...       -1   
freq                                                  310     3130   

           album.8 album.9           album.10  album.11 album.12  \
count        18061  106575             105550    106575   100067   
unique         761    2389              14299       170        6   
top     Joe Belock      []  microSong Entries        10    Album   
freq           855   83549                310      6045    87549   

                     artist             artist.1      artist.2  \
count                 22712                 5376         14272   
unique                   77                   58           755   
top     2007-01-01 00:00:00  2016-01-01 00:00:00  HUSH Records   
freq                   1789                  479           604   

                                                 artist.3  artist.4  \
count                                               71157    106575   
unique                                               6085        52   
top     <p><span style="color: #333333; font-family: G...         0   
freq                                                  745     59914   

                   artist.5  artist.6  artist.7      artist.8      artist.9  \
count                105719    106575    106575  44545.000000         70211   
unique                15971       214     17055   1613.000000          2330   
top     2013-03-31 02:17:41         0     15891     40.692455  Brooklyn, NY   
freq                    745     15414       745    890.000000          2327   

           artist.10    ...    artist.14  \
count   44545.000000    ...       106575   
unique   1601.000000    ...        15661   
top       -73.990364    ...           []   
freq      890.000000    ...         3061   

                                       artist.15  \
count                                      79257   
unique                                      6643   
top     https://soundcloud.com/konstantin-trokay   
freq                                         745   

                                         artist.16       set   set.1   track  \
count                                         5582    106575  106575  106575   
unique                                         390         4       4   12172   
top     http://en.wikipedia.org/wiki/Josh_Woodward  training   large  320000   
freq                                           284     84353   81574   49094   

       track.1            track.2              track.3              track.4  \
count   106575               3671               106575                 6160   
unique      28                506                86170                  774   
top          0  konstantin trokai  2009-06-25 11:36:04  2008-11-26 00:00:00   
freq     88386                541                    4                  700   

       track.5 track.6 track.7  track.8  track.9  \
count   106575  106575   49599   106575   106575   
unique    3366     329      17     4769     4152   
top        180       0    Rock     [21]     [21]   
freq       507   35944   14182     2735     2735   

                                                 track.10 track.11 track.12  \
count                               

In [35]:
pd.set_option('display.max_columns', None)  # Unlimited columns
tracks.head()

Unnamed: 0     album              album.1              album.2   album.3  \
0        NaN  comments         date_created        date_released  engineer   
1   track_id       NaN                  NaN                  NaN       NaN   
2          2         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
3          3         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
4          5         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   

     album.4 album.5      album.6  album.7   album.8 album.9  \
0  favorites      id  information  listens  producer    tags   
1        NaN     NaN          NaN      NaN       NaN     NaN   
2          4       1      <p></p>     6073       NaN      []   
3          4       1      <p></p>     6073       NaN      []   
4          4       1      <p></p>     6073       NaN      []   

               album.10 album.11 album.12               artist  \
0                 title   tracks     type    active_year_begin   
1                   NaN      NaN      NaN                  NaN   
2  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   
3  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   
4  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   

          artist.1           artist.2  \
0  active_year_end  associated_labels   
1              NaN                NaN   
2              NaN                NaN   
3              NaN                NaN   
4              NaN                NaN   

                                            artist.3  artist.4  \
0                                                bio  comments   
1                                                NaN       NaN   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0   
4  <p>A Way Of Life, A Collective of Hip-Hop from...         0   

              artist.5   artist.6 artist.7    artist.8    artist.9  \
0         date_created  favorites       id    latitude    location   
1                  NaN        NaN      NaN         NaN         NaN   
2  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   
3  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   
4  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   

     artist.10                                          artist.11 artist.12  \
0    longitude                                            members      name   
1          NaN                                                NaN       NaN   
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   

                                           artist.13 artist.14  \
0                                   related_projects      tags   
1                                                NaN       NaN   
2  The list of past projects is 2 long but every1...  ['awol']   
3  The list of past projects is 2 long but every1...  ['awol']   
4  The list of past projects is 2 long but every1...  ['awol']   

                                 artist.15       artist.16       set   set.1  \
0                                  website  wikipedia_page     split  subset   
1                                      NaN             NaN       NaN     NaN   
2  http://www.AzillionRecords.blogspot.com             NaN  training   small   
3  http://www.AzillionRecords.blogspot.com             NaN  training  medium   
4  http://www.AzillionRecords.blogspot.com             NaN  training   small   

      track   track.1   track.2              track.3              track.4  \
0  bit_rate  comments  composer         date_created        date_recorded   
1       NaN       NaN       NaN                  NaN                  NaN   
2    256000         0       NaN  2008-11-26 01:48:12  2008-11-26 00:00:00   
3    256000         0    

In [37]:
tracks.shape
tracks

Unnamed: 0     album              album.1              album.2  \
0             NaN  comments         date_created        date_released   
1        track_id       NaN                  NaN                  NaN   
2               2         0  2008-11-26 01:44:45  2009-01-05 00:00:00   
3               3         0  2008-11-26 01:44:45  2009-01-05 00:00:00   
4               5         0  2008-11-26 01:44:45  2009-01-05 00:00:00   
5              10         0  2008-11-26 01:45:08  2008-02-06 00:00:00   
6              20         0  2008-11-26 01:45:05  2009-01-06 00:00:00   
7              26         0  2008-11-26 01:45:05  2009-01-06 00:00:00   
8              30         0  2008-11-26 01:45:05  2009-01-06 00:00:00   
9              46         0  2008-11-26 01:45:05  2009-01-06 00:00:00   
10             48         0  2008-11-26 01:45:05  2009-01-06 00:00:00   
11            134         0  2008-11-26 01:44:45  2009-01-05 00:00:00   
12            135         1  2008-11-26 01:49:19  2009-01-07 00:00:00   
13            136         1  2008-11-26 01:49:19  2009-01-07 00:00:00   
14            137         1  2008-11-26 01:49:35  2006-12-01 00:00:00   
15            138         1  2008-11-26 01:49:35  2006-12-01 00:00:00   
16            139         0  2008-11-26 01:49:57  2009-01-16 00:00:00   
17            140         1  2008-11-26 01:49:59  2007-05-22 00:00:00   
18            141         0  2008-11-26 01:49:57  2009-01-16 00:00:00   
19            142         0  2008-11-26 01:50:03  2005-01-25 00:00:00   
20            144         0  2008-11-26 01:50:07  2009-01-06 00:00:00   
21            145         0  2008-11-26 01:50:07  2009-01-06 00:00:00   
22            146         0  2008-11-26 01:50:13  1995-01-01 00:00:00   
23            147         0  2008-11-26 01:50:13  1995-01-01 00:00:00   
24            148         0  2008-11-26 01:50:19  2009-01-15 00:00:00   
25            149         0  2008-11-26 01:50:25  2009-01-09 00:00:00   
26            150         0  2008-11-26 01:50:25  2009-01-09 00:00:00   
27            151         0  2008-11-26 01:50:46  2009-01-06 00:00:00   
28            152         0  2008-11-26 01:50:46  2009-01-06 00:00:00   
29            153         0  2008-11-26 01:50:50  2005-06-07 00:00:00   
...           ...       ...                  ...                  ...   
106546     155290         0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106547     155291         0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106548     155292         0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106549     155293         0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106550     155294         0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106551     155295         0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106552     155296         0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106553     155297         0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106554     155298         0  2017-03-30 10:45:13                  NaN   
106555     155299         0  2017-03-30 10:45:13                  NaN   
106556     155300         0  2017-03-30 10:45:13                  NaN   
106557     155301         0  2017-03-30 10:45:13                  NaN   
106558     155302         0  2017-03-30 10:45:13                  NaN   
106559     155303         0  2017-03-30 10:45:13                  NaN   
106560     155304         0  2017-03-30 10:45:13                  NaN   
106561     155305         0  2017-03-30 10:45:13                  NaN   
106562     155306         0  2017-03-30 10:45:13                  NaN   
106563     155307         0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106564     155308         0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106565     155309         0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106566     155310         0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106567     155311         0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106568     155312         0  2017-03-30 12:51:05  2017-03-27 00:0

In [80]:
new_header = tracks.iloc[0] #grab the first row for the header
tracks_new = tracks[1:] #take the data less the header row
tracks_new.columns = new_header #set the header row as the df header

tracks_new = tracks_new[1:]
tracks_new

0          NaN comments         date_created        date_released  \
2            2        0  2008-11-26 01:44:45  2009-01-05 00:00:00   
3            3        0  2008-11-26 01:44:45  2009-01-05 00:00:00   
4            5        0  2008-11-26 01:44:45  2009-01-05 00:00:00   
5           10        0  2008-11-26 01:45:08  2008-02-06 00:00:00   
6           20        0  2008-11-26 01:45:05  2009-01-06 00:00:00   
7           26        0  2008-11-26 01:45:05  2009-01-06 00:00:00   
8           30        0  2008-11-26 01:45:05  2009-01-06 00:00:00   
9           46        0  2008-11-26 01:45:05  2009-01-06 00:00:00   
10          48        0  2008-11-26 01:45:05  2009-01-06 00:00:00   
11         134        0  2008-11-26 01:44:45  2009-01-05 00:00:00   
12         135        1  2008-11-26 01:49:19  2009-01-07 00:00:00   
13         136        1  2008-11-26 01:49:19  2009-01-07 00:00:00   
14         137        1  2008-11-26 01:49:35  2006-12-01 00:00:00   
15         138        1  2008-11-26 01:49:35  2006-12-01 00:00:00   
16         139        0  2008-11-26 01:49:57  2009-01-16 00:00:00   
17         140        1  2008-11-26 01:49:59  2007-05-22 00:00:00   
18         141        0  2008-11-26 01:49:57  2009-01-16 00:00:00   
19         142        0  2008-11-26 01:50:03  2005-01-25 00:00:00   
20         144        0  2008-11-26 01:50:07  2009-01-06 00:00:00   
21         145        0  2008-11-26 01:50:07  2009-01-06 00:00:00   
22         146        0  2008-11-26 01:50:13  1995-01-01 00:00:00   
23         147        0  2008-11-26 01:50:13  1995-01-01 00:00:00   
24         148        0  2008-11-26 01:50:19  2009-01-15 00:00:00   
25         149        0  2008-11-26 01:50:25  2009-01-09 00:00:00   
26         150        0  2008-11-26 01:50:25  2009-01-09 00:00:00   
27         151        0  2008-11-26 01:50:46  2009-01-06 00:00:00   
28         152        0  2008-11-26 01:50:46  2009-01-06 00:00:00   
29         153        0  2008-11-26 01:50:50  2005-06-07 00:00:00   
30         154        0  2008-11-26 01:50:50  2005-06-07 00:00:00   
31         155        0  2008-11-26 01:51:00  2009-01-06 00:00:00   
...        ...      ...                  ...                  ...   
106546  155290        0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106547  155291        0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106548  155292        0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106549  155293        0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106550  155294        0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106551  155295        0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106552  155296        0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106553  155297        0  2017-03-30 09:50:32  2017-03-30 00:00:00   
106554  155298        0  2017-03-30 10:45:13                  NaN   
106555  155299        0  2017-03-30 10:45:13                  NaN   
106556  155300        0  2017-03-30 10:45:13                  NaN   
106557  155301        0  2017-03-30 10:45:13                  NaN   
106558  155302        0  2017-03-30 10:45:13                  NaN   
106559  155303        0  2017-03-30 10:45:13                  NaN   
106560  155304        0  2017-03-30 10:45:13                  NaN   
106561  155305        0  2017-03-30 10:45:13                  NaN   
106562  155306        0  2017-03-30 10:45:13                  NaN   
106563  155307        0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106564  155308        0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106565  155309        0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106566  155310        0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106567  155311        0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106568  155312        0  2017-03-30 12:51:05  2017-03-27 00:00:00   
106569  155314        0  2017-03-30 15:20:35  2017-02-17 00:00:00   
106570  155315        0  2017-03-30 15:20:35  2017-02-17 00:00:00   
106571  155316        0  2017-03-30 15:20:35  2017-02-17 00:00:00  

In [43]:
tracks_new.isna().sum()

0
NaN                       0
comments                  0
date_created           3529
date_released         36280
engineer              91279
favorites                 0
id                        0
information           23425
listens                   0
producer              88514
tags                      0
title                  1025
tracks                    0
type                   6508
active_year_begin     83863
active_year_end      101199
associated_labels     92303
bio                   35418
comments                  0
date_created            856
favorites                 0
id                        0
latitude              62030
location              36364
longitude             62030
members               59725
name                      0
related_projects      93422
tags                      0
website               27318
wikipedia_page       100993
split                     0
subset                    0
bit_rate                  0
comments                  0
composer          

In [0]:
tracks_new['genres'].value_counts()

In [0]:
tracks_new['genre_top'].value_counts()

In [0]:
genres = pd.read_csv('fma_metadata/genres.csv')
genres.head(200)

In [98]:
#favorites is 31%

tracks_1 = tracks_new[['genre_top','favorites']]
tracks_1 = tracks_1.dropna(how='any',axis=0)

X = tracks_1['favorites']
y = tracks_1['genre_top']

X_train,X_test,Y_train,Y_test = train_test_split(X,y, test_size=.3,random_state=42)

model2 = LogisticRegression(random_state=42, max_iter=8000)
model2.fit(X_train,Y_train)
model2.score(X_test,Y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.3086021505376344

This is the biggest data you've played with so far, and while it does generally fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

## Resources and stretch goals

- Check out the other .csv files from the FMA dataset, and see if you can join them or otherwise fit interesting models with them
- [Logistic regression from scratch in numpy](https://blog.goodaudience.com/logistic-regression-from-scratch-in-numpy-5841c09e425f) - if you want to dig in a bit more to both the code and math (also takes a gradient descent approach, introducing the logistic loss function)
- Create a visualization to show predictions of your model - ideally show a confidence interval based on error!
- Check out and compare classification models from scikit-learn, such as [SVM](https://scikit-learn.org/stable/modules/svm.html#classification), [decision trees](https://scikit-learn.org/stable/modules/tree.html#classification), and [naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html). The underlying math will vary significantly, but the API (how you write the code) and interpretation will actually be fairly similar.
- Sign up for [Kaggle](https://kaggle.com), and find a competition to try logistic regression with
- (Not logistic regression related) If you enjoyed the assignment, you may want to read up on [music informatics](https://en.wikipedia.org/wiki/Music_informatics), which is how those audio features were actually calculated. The FMA includes the actual raw audio, so (while this is more of a longterm project than a stretch goal, and won't fit in Colab) if you'd like you can check those out and see what sort of deeper analysis you can do.