<a href="https://colab.research.google.com/github/invegat/DS-Unit-2-Sprint-3-Advanced-Regression/blob/master/module1-logistic-regression/LS_DS_231_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

In [0]:
!pip install -U matplotlib

Requirement already up-to-date: matplotlib in /usr/local/lib/python3.6/dist-packages (3.0.2)


In [0]:

%matplotlib inline  
# %matplotlib notebook
# %pylab
import matplotlib
matplotlib._version.sys.version

'3.6.7 (default, Oct 22 2018, 11:32:17) \n[GCC 8.2.0]'

In [0]:
!pip install kaggle

In [0]:
# Note - you'll also have to sign up for Kaggle and authorize the API
# https://github.com/Kaggle/kaggle-api#api-credentials

# This essentially means uploading a kaggle.json file
# For Colab we can have it in Google Drive
from google.colab import drive
drive.mount('/content/drive')
%env KAGGLE_CONFIG_DIR=/content/drive/My Drive/downloads/

# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
env: KAGGLE_CONFIG_DIR=/content/drive/My Drive/downloads/
train.csv: Skipping, found more recently modified local copy (use --force to force download)
test.csv: Skipping, found more recently modified local copy (use --force to force download)
gender_submission.csv: Skipping, found more recently modified local copy (use --force to force download)


In [0]:
# How would we try to do this with linear regression?
import pandas as pd

train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

train_df.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [0]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [0]:
from sklearn.linear_model import LinearRegression

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550917

In [0]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [0]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [0]:
import numpy as np

test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

In [0]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(solver='liblinear').fit(X, y)
log_reg.score(X, y)

0.7103825136612022

In [0]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
log_reg.predict(test_case)[0]

1

In [0]:
help(log_reg.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.logistic.LogisticRegression instance
    Predict class labels for samples in X.
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape [n_samples]
        Predicted class label per sample.



In [0]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [0]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [0]:
log_reg.intercept_

array([1.45878264])

In [0]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
  return 1 / (1 + np.e**(-x))

In [0]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

So, clearly a more appropriate model in this situation! For more on the math, [see this Wikipedia example](https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study).

For live - let's tackle [another classification dataset on absenteeism](http://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work) - it has 21 classes, but remember, scikit-learn LogisticRegression automatically handles more than two classes. How? By essentially treating each label as different (1) from some base class (0).

In [0]:
# Live - let's try absenteeism!
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/00445/Absenteeism_at_work_AAA.zip
!unzip Absenteeism_at_work_AAA.zip

--2019-01-18 22:31:52--  http://archive.ics.uci.edu/ml/machine-learning-databases/00445/Absenteeism_at_work_AAA.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66136 (65K) [application/zip]
Saving to: ‘Absenteeism_at_work_AAA.zip.1’

Absenteeism_at_work 100%[===================>]  64.59K   179KB/s    in 0.4s    

2019-01-18 22:31:53 (179 KB/s) - ‘Absenteeism_at_work_AAA.zip.1’ saved [66136/66136]

Archive:  Absenteeism_at_work_AAA.zip
replace Absenteeism_at_work.arff? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace Absenteeism_at_work.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace Absenteeism_at_work.xls? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace Attribute Information.docx? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace UCI_ABS_TEXT.docx? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [0]:
!head Absenteeism_at_work.csv

ID;Reason for absence;Month of absence;Day of the week;Seasons;Transportation expense;Distance from Residence to Work;Service time;Age;Work load Average/day ;Hit target;Disciplinary failure;Education;Son;Social drinker;Social smoker;Pet;Weight;Height;Body mass index;Absenteeism time in hours
11;26;7;3;1;289;36;13;33;239.554;97;0;1;2;1;0;1;90;172;30;4
36;0;7;3;1;118;13;18;50;239.554;97;1;1;1;1;0;0;98;178;31;0
3;23;7;4;1;179;51;18;38;239.554;97;0;1;0;1;0;0;89;170;31;2
7;7;7;5;1;279;5;14;39;239.554;97;0;1;2;1;1;0;68;168;24;4
11;23;7;5;1;289;36;13;33;239.554;97;0;1;2;1;0;1;90;172;30;2
3;23;7;6;1;179;51;18;38;239.554;97;0;1;0;1;0;0;89;170;31;2
10;22;7;6;1;361;52;3;28;239.554;97;0;1;1;1;0;4;80;172;27;8
20;23;7;6;1;260;50;11;36;239.554;97;0;1;4;1;0;0;65;168;23;4
14;19;7;2;1;155;12;14;34;239.554;97;0;1;2;1;0;0;95;196;25;40


In [0]:
absent_df = pd.read_table('Absenteeism_at_work.csv', sep=';')
absent_df.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day             ...              Disciplinary failure  \
0                 239.554            ...                                 0   
1                 239.554            ...                                 1   
2                 239.554            ...                                 0   
3                 239.554            ...                                 0   
4                 239.554            ...                                 0   

   Education  Son  Social drinker  Social smoker  Pet  Weight  Height  \
0          1    2               1              0    1      90     172   
1          1    1               1              0    0      98     178   
2          1    0               1              0    0      89     170   
3          1    2               1              1    0      68     168   
4          1    2               1              0    1      90     172   

   Body mass index  Absenteeism time in hours  
0               30                          4  
1               31                          0  
2               31                          2  
3               24                          4  
4               30                          2  

[5 rows x 21 columns]

In [0]:
X = absent_df.drop('Reason for absence', axis='columns')
y = absent_df['Reason for absence']

absent_log1 = LogisticRegression(solver='liblinear', multi_class='auto').fit(X, y)
absent_log1.score(X, y)

0.5013513513513513

In [0]:
absent_log1.coef_

array([[-1.27508146e-02, -2.20793886e-01, -4.08404457e-02,
         4.22616389e-01,  7.64613632e-03, -6.18658809e-03,
        -3.11523480e-02,  5.52309565e-02, -1.01707258e-02,
        -1.14781041e-01,  2.51984519e+00,  1.41303285e-02,
         3.56702636e-01,  2.27778616e-01,  1.80478520e-01,
         1.33441356e-01, -9.82098540e-03,  5.23702470e-02,
         7.24744784e-02, -3.15221513e+00],
       [ 5.11128074e-02,  1.77166203e-01, -5.01201750e-01,
        -9.34413067e-02,  8.70070989e-03,  2.90683453e-02,
        -8.19496921e-02,  1.30910624e-01,  3.69193210e-03,
         3.58478924e-02, -7.77198534e-01,  9.21419989e-01,
         2.74046853e-01, -6.53744541e-01, -2.74959514e-01,
        -4.46143318e-01,  1.88638790e-01, -7.60409657e-02,
        -6.85430554e-01,  4.55734002e-03],
       [ 1.74477093e-01,  5.91768593e-01,  4.46355493e-02,
         4.29016838e-01,  5.97802716e-02, -2.02281583e-01,
        -4.44906133e-01, -2.65239556e-01,  8.55486140e-03,
        -4.07755000e-01, -6.7

## Assignment - real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from datetime import datetime
import math
from scipy.stats import mode
from sklearn.preprocessing import StandardScaler
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import statsmodels.api as s

/usr/local/lib/python3.6/dist-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [5]:
!wget https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
!unzip fma_metadata.zip

--2019-01-19 21:51:23--  https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
Resolving os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)... 86.119.28.13, 2001:620:5ca1:2ff::ce53
Connecting to os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)|86.119.28.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 358412441 (342M) [application/zip]
Saving to: ‘fma_metadata.zip’

fma_metadata.zip    100%[===================>] 341.81M  25.0MB/s    in 17s     

2019-01-19 21:51:41 (20.0 MB/s) - ‘fma_metadata.zip’ saved [358412441/358412441]

Archive:  fma_metadata.zip
 bunzipping: fma_metadata/README.txt  
 bunzipping: fma_metadata/checksums  
 bunzipping: fma_metadata/not_found.pickle  
 bunzipping: fma_metadata/raw_genres.csv  
 bunzipping: fma_metadata/raw_albums.csv  
 bunzipping: fma_metadata/raw_artists.csv  
 bunzipping: fma_metadata/raw_tracks.csv  
 bunzipping: fma_metadata/tracks.csv  
 bunzipping: fma_metadata/genres.csv  
 bunzipping: fma_metadata/raw_echonest.cs

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from datetime import datetime
import math
from scipy.stats import mode
from sklearn.preprocessing import StandardScaler
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import statsmodels.api as sm
import time

/usr/local/lib/python3.6/dist-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [12]:
tracks = pd.read_csv('fma_metadata/tracks.csv', header=1)
tracks = tracks.iloc[1:]
pd.set_option('display.max_columns', None)  # Unlimited columns
tracks.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0  comments         date_created        date_released engineer  \
1          2       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
2          3       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3          5       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4         10       0.0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
5         20       0.0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN   

   favorites   id                                information  listens  \
1        4.0  1.0                                    <p></p>   6073.0   
2        4.0  1.0                                    <p></p>   6073.0   
3        4.0  1.0                                    <p></p>   6073.0   
4        4.0  6.0                                        NaN  47632.0   
5        2.0  4.0  <p> "spiritual songs" from Nicky Cook</p>   2710.0   

  producer tags                 title  tracks   type    active_year_begin  \
1      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
2      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
3      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
4      NaN   []     Constant Hitmaker     2.0  Album                  NaN   
5      NaN   []                 Niris    13.0  Album  1990-01-01 00:00:00   

       active_year_end                                  associated_labels  \
1                  NaN                                                NaN   
2                  NaN                                                NaN   
3                  NaN                                                NaN   
4                  NaN  Mexican Summer, Richie Records, Woodsist, Skul...   
5  2011-01-01 00:00:00                                                NaN   

                                                 bio  comments.1  \
1  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
4  <p><span style="font-family:Verdana, Geneva, A...         3.0   
5  <p>Songs written by: Nicky Cook</p>\n<p>VOCALS...         2.0   

        date_created.1  favorites.1  id.1   latitude            location  \
1  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
2  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
3  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
4  2008-11-26 01:42:55         74.0   6.0        NaN                 NaN   
5  2008-11-26 01:42:52         10.0   4.0  51.895927  Colchester England   

   longitude                                            members        name  \
1 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
2 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
3 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
4        NaN                           Kurt Vile, the Violators   Kurt Vile   
5   0.891874                                       Nicky Cook\n  Nicky Cook   

                                    related_projects  \
1  The list of past projects is 2 long but every1...   
2  The list of past projects is 2 long but every1...   
3  The list of past projects is 2 long but every1...   
4                                                NaN   
5                                                NaN   

                                              tags.1  \
1                                           ['awol']   
2                                           ['awol']   
3                                           ['awol']   
4                            ['philly', 'kurt vile']   
5  ['instrumentals', 'experimental pop', 'post pu...   

                                   website wikipedia_page     split  subset  \
1  http://www.AzillionRecords.blogspot.com            NaN  training   small   
2

In [3]:
tracks.describe()

comments      favorites             id       listens  \
count  106574.000000  106574.000000  106574.000000  1.065740e+05   
mean        0.394946       1.286927   12826.933914  3.212031e+04   
std         2.268915       3.133035    6290.261805  1.478532e+05   
min        -1.000000      -1.000000      -1.000000 -1.000000e+00   
25%         0.000000       0.000000    7793.000000  3.361000e+03   
50%         0.000000       0.000000   13374.000000  8.982000e+03   
75%         0.000000       1.000000   18203.000000  2.363500e+04   
max        53.000000      61.000000   22940.000000  3.564243e+06   

              tracks     comments.1    favorites.1           id.1  \
count  106574.000000  106574.000000  106574.000000  106574.000000   
mean       19.721452       1.894702      30.041915   12036.770404   
std        39.943673       6.297679     100.511408    6881.420867   
min        -1.000000      -1.000000      -1.000000       1.000000   
25%         7.000000       0.000000       1.000000    6443.000000   
50%        11.000000       0.000000       5.000000   12029.500000   
75%        17.000000       1.000000      16.000000   18011.000000   
max       652.000000      79.000000     963.000000   24357.000000   

           latitude     longitude       bit_rate     comments.2  \
count  44544.000000  44544.000000  106574.000000  106574.000000   
mean      39.901626    -38.668642  263274.695048       0.031621   
std       18.240860     65.237220   67623.443584       0.321993   
min      -45.878760   -157.526855      -1.000000       0.000000   
25%       39.271398    -79.997459  192000.000000       0.000000   
50%       41.387917    -73.554431  299914.000000       0.000000   
75%       48.856930      4.351710  320000.000000       0.000000   
max       67.286005    175.277000  448000.000000      37.000000   

            duration    favorites.2      interest      listens.1  \
count  106574.000000  106574.000000  1.065740e+05  106574.000000   
mean      277.849100       3.182521  3.541310e+03    2329.353548   
std       305.518553      13.513820  1.901743e+04    8028.070647   
min         0.000000       0.000000  2.000000e+00       0.000000   
25%       149.000000       0.000000  5.990000e+02     292.000000   
50%       216.000000       1.000000  1.314000e+03     764.000000   
75%       305.000000       3.000000  3.059000e+03    2018.000000   
max     18350.000000    1482.000000  3.293557e+06  543252.000000   

              number  
count  106574.000000  
mean        8.260945  
std        15.243271  
min         0.000000  
25%         2.000000  
50%         5.000000  
75%         9.000000  
max       255.000000

In [4]:
tracks.shape

(106574, 53)

In [5]:
list(tracks.columns.values).index('genre_top')

40

In [6]:
unique_genre = tracks.genre_top.unique()
unique_genre

array(['Hip-Hop', 'Pop', nan, 'Rock', 'Experimental', 'Folk', 'Jazz',
       'Electronic', 'Spoken', 'International', 'Soul-RnB', 'Blues',
       'Country', 'Classical', 'Old-Time / Historic', 'Instrumental',
       'Easy Listening'], dtype=object)

In [7]:
len(unique_genre)

17

In [0]:
def get_binary(cat_types, row, index):
  cell = row.iloc[index]
  # print(str(type(cell)) == "<class 'str'>" , type(cell), cell)
  if str(type(cell)) != "<class 'str'>":
    #print('found Nan')
    pattern = '00000000'
  else:
    # print(f'found non-NaN {cell}')
    pattern = f'{(cat_types.index(cell) + 1):08b}'
  return pd.Series([int(pattern[7-j]) for j in range(0,min(8,int(np.log2(len(types))) + 1))])


In [22]:
df = tracks
cats = ['genre_top']
bdf = pd.DataFrame(df)
st = time.perf_counter()
for c in cats:
    index = list(tracks.columns.values).index(c)
    cl = c[0].lower() + c[1:] + '_'
    types = df[c].unique().tolist()
    bdf[[(cl + str(j)) for j in range(0,min(
        8,int(np.log2(len(types))) + 1)) ]] = \
       bdf.apply(lambda row: get_binary(types, row, index), axis=1)
elapsed = time.perf_counter() - st
print(f"apply executed in {elapsed:0.2f} seconds.")
dfbc = bdf.drop(cats,inplace=False, axis=1)

apply executed in 24.79 seconds.


In [0]:
# df = tracks
# cats = ['genre_top']
# for c in cats:
#     cl = c[0].lower() + c[1:] + '-'
#     types = df[c].unique().tolist() 
#     for i in range(0,len(types)):
#       if len(df[df[c] == types[i]]) == 0:
#         continue
#       patterns = df[df[c] == types[i]][c].apply(lambda s: \
#           ('00000000' if pd.isnull(s) else f'{(types.index(s) + 1):08b}'))
#       #tdf['gentre_top_0']= pd.Series([int(p[0]) for p in patterns])
#       print(type(patterns),patterns.shape)
#       for j in range(5):
#         print(patterns.iat[j])
#       for j in range(0,min(8,int(np.log2(len(types))) + 1)):
# #          if j == 0:
# #            print(len([int(p[j]) for p in patterns]))
# #            print(len(df.loc[df[c] == types[i],c]))
# #          print(f"i {i} j {j} types[i]: {types[i]} clj: {cl + str(j)}")
# #          df.loc[df[c] == types[i],c][cl + str(j)] = pd.Series([int(p[j]) for p in patterns])
#           df[cl + str(j)] = pd.Series([int(p[j]) for p in patterns])
# dfbc = df.drop(cats,inplace=False, axis=1)
# # dfbc = dfbc.join(tdf)
# dfbc.head()

In [18]:
dfbc.head(5)

Unnamed: 0  comments         date_created        date_released engineer  \
1          2       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
2          3       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3          5       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4         10       0.0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
5         20       0.0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN   

   favorites   id                                information  listens  \
1        4.0  1.0                                    <p></p>   6073.0   
2        4.0  1.0                                    <p></p>   6073.0   
3        4.0  1.0                                    <p></p>   6073.0   
4        4.0  6.0                                        NaN  47632.0   
5        2.0  4.0  <p> "spiritual songs" from Nicky Cook</p>   2710.0   

  producer tags                 title  tracks   type    active_year_begin  \
1      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
2      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
3      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
4      NaN   []     Constant Hitmaker     2.0  Album                  NaN   
5      NaN   []                 Niris    13.0  Album  1990-01-01 00:00:00   

       active_year_end                                  associated_labels  \
1                  NaN                                                NaN   
2                  NaN                                                NaN   
3                  NaN                                                NaN   
4                  NaN  Mexican Summer, Richie Records, Woodsist, Skul...   
5  2011-01-01 00:00:00                                                NaN   

                                                 bio  comments.1  \
1  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
4  <p><span style="font-family:Verdana, Geneva, A...         3.0   
5  <p>Songs written by: Nicky Cook</p>\n<p>VOCALS...         2.0   

        date_created.1  favorites.1  id.1   latitude            location  \
1  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
2  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
3  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
4  2008-11-26 01:42:55         74.0   6.0        NaN                 NaN   
5  2008-11-26 01:42:52         10.0   4.0  51.895927  Colchester England   

   longitude                                            members        name  \
1 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
2 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
3 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
4        NaN                           Kurt Vile, the Violators   Kurt Vile   
5   0.891874                                       Nicky Cook\n  Nicky Cook   

                                    related_projects  \
1  The list of past projects is 2 long but every1...   
2  The list of past projects is 2 long but every1...   
3  The list of past projects is 2 long but every1...   
4                                                NaN   
5                                                NaN   

                                              tags.1  \
1                                           ['awol']   
2                                           ['awol']   
3                                           ['awol']   
4                            ['philly', 'kurt vile']   
5  ['instrumentals', 'experimental pop', 'post pu...   

                                   website wikipedia_page     split  subset  \
1  http://www.AzillionRecords.blogspot.com            NaN  training   small   
2

This is the biggest data you've played with so far, and while it does generally fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

## Resources and stretch goals

- Check out the other .csv files from the FMA dataset, and see if you can join them or otherwise fit interesting models with them
- [Logistic regression from scratch in numpy](https://blog.goodaudience.com/logistic-regression-from-scratch-in-numpy-5841c09e425f) - if you want to dig in a bit more to both the code and math (also takes a gradient descent approach, introducing the logistic loss function)
- Create a visualization to show predictions of your model - ideally show a confidence interval based on error!
- Check out and compare classification models from scikit-learn, such as [SVM](https://scikit-learn.org/stable/modules/svm.html#classification), [decision trees](https://scikit-learn.org/stable/modules/tree.html#classification), and [naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html). The underlying math will vary significantly, but the API (how you write the code) and interpretation will actually be fairly similar.
- Sign up for [Kaggle](https://kaggle.com), and find a competition to try logistic regression with
- (Not logistic regression related) If you enjoyed the assignment, you may want to read up on [music informatics](https://en.wikipedia.org/wiki/Music_informatics), which is how those audio features were actually calculated. The FMA includes the actual raw audio, so (while this is more of a longterm project than a stretch goal, and won't fit in Colab) if you'd like you can check those out and see what sort of deeper analysis you can do.