# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

In [2]:
!pip install kaggle

In [3]:
# Note - you'll also have to sign up for Kaggle and authorize the API
# https://github.com/Kaggle/kaggle-api#api-credentials

%env KAGGLE_CONFIG_DIR=../../../Kaggle

# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

env: KAGGLE_CONFIG_DIR=../../../Kaggle
train.csv: Skipping, found more recently modified local copy (use --force to force download)
test.csv: Skipping, found more recently modified local copy (use --force to force download)
gender_submission.csv: Skipping, found more recently modified local copy (use --force to force download)


In [4]:
# How would we try to do this with linear regression?
import pandas as pd

train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

train_df.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [5]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [6]:
from sklearn.linear_model import LinearRegression

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550917

In [7]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [8]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [9]:
import numpy as np

test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

In [10]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

/Users/zach/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7103825136612022

In [11]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
log_reg.predict(test_case)[0]

1

In [13]:
help(log_reg.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.logistic.LogisticRegression instance
    Predict class labels for samples in X.
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape [n_samples]
        Predicted class label per sample.



In [14]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [15]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [16]:
log_reg.intercept_

array([1.45878264])

In [17]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
  return 1 / (1 + np.e**(-x))

In [18]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

So, clearly a more appropriate model in this situation! For more on the math, [see this Wikipedia example](https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study).

For live - let's tackle [another classification dataset on absenteeism](http://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work) - it has 21 classes, but remember, scikit-learn LogisticRegression automatically handles more than two classes. How? By essentially treating each label as different (1) from some base class (0).

In [30]:
# Live - let's try absenteeism!

## Assignment - real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

In [20]:
# !curl https://os.unil.cloud.switch.ch/fma/fma_metadata.zip --output fma_metadata.zip
!7za x fma_metadata.zip 


7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
  0M Sca        1 file, 358412441 bytes (342 MiB)

Extracting archive: fma_metadata.zip
--
Path = fma_metadata.zip
Type = zip
Physical Size = 358412441

    
Would you like to replace the existing file:
  Path:     ./fma_metadata/README.txt
  Size:     256 bytes (1 KiB)
  Modified: 2017-04-01 00:00:00
with the file from archive:
  Path:     fma_metadata/README.txt
  Size:     256 bytes (1 KiB)
  Modified: 2017-04-01 00:00:00
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? ^C
(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 

In [31]:
tracks = pd.read_csv('fma_metadata/tracks.csv')

/Users/zach/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,1,5,6,8,12,18,20,21,22,24,33,34,38,39,44,47,49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [32]:
tracks.describe()

Unnamed: 0   album              album.1              album.2  \
count      106575  106575               103046                70295   
unique     106575      29                14341                 3670   
top         21055       0  2015-01-26 13:04:57  2008-01-01 00:00:00   
freq            1   71187                  310                  667   

               album.3  album.4  album.5  \
count            15296   106575   106575   
unique             623       65    14929   
top     Ernie Indradat        0       -1   
freq               876    45753      805   

                                                  album.6  album.7  \
count                                               83150   106575   
unique                                              11076    11351   
top     <p class="p1" style="margin: 0px; padding: 8px...       -1   
freq                                                  310     3130   

           album.8 album.9           album.10  album.11 album.12  \
count        18061  106575             105550    106575   100067   
unique         761    2389              14299       170        6   
top     Joe Belock      []  microSong Entries        10    Album   
freq           855   83549                310      6045    87549   

                     artist             artist.1      artist.2  \
count                 22712                 5376         14272   
unique                   77                   58           755   
top     2007-01-01 00:00:00  2016-01-01 00:00:00  HUSH Records   
freq                   1789                  479           604   

                                                 artist.3  artist.4  \
count                                               71157    106575   
unique                                               6085        52   
top     <p><span style="color: #333333; font-family: G...         0   
freq                                                  745     59914   

                   artist.5  artist.6  artist.7      artist.8      artist.9  \
count                105719    106575    106575  44545.000000         70211   
unique                15971       214     17055   1613.000000          2330   
top     2013-03-31 02:17:41         0     15891     40.692455  Brooklyn, NY   
freq                    745     15414       745    890.000000          2327   

           artist.10          artist.11 artist.12  \
count   44545.000000              46850    106575   
unique   1601.000000               4016     16295   
top       -73.990364  Konstantin Trokay   Kosta T   
freq      890.000000                745       745   

                                                artist.13 artist.14  \
count                                               13153    106575   
unique                                                753     15661   
top     Ratatat, Lullatone, Nightmares On Wax, Air, Mo...        []   
freq                                                  604      3061   

                                       artist.15  \
count                                      79257   
unique                                      6643   
top     https://soundcloud.com/konstantin-trokay   
freq                                         745   

                                         artist.16       set   set.1   track  \
count                                         5582    106575  106575  106575   
unique                                         390         4       4   12172   
top     http://en.wikipedia.org/wiki/Josh_Woodward  training   large  320000   
freq                                           284     84353   81574   49094   

        track.1            track.2              track.3              track.4  \
count    106575               3671               106575                 6160   
unique       28                506                86170                  774   
top           0  konstantin trokai  2009-03-05 09:45:49  2008-11-26 00:00:00   
freq      88386                541                 

In [33]:
pd.set_option('display.max_columns', None)  # Unlimited columns
tracks.head()

Unnamed: 0     album              album.1              album.2   album.3  \
0        NaN  comments         date_created        date_released  engineer   
1   track_id       NaN                  NaN                  NaN       NaN   
2          2         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
3          3         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
4          5         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   

     album.4 album.5      album.6  album.7   album.8 album.9  \
0  favorites      id  information  listens  producer    tags   
1        NaN     NaN          NaN      NaN       NaN     NaN   
2          4       1      <p></p>     6073       NaN      []   
3          4       1      <p></p>     6073       NaN      []   
4          4       1      <p></p>     6073       NaN      []   

               album.10 album.11 album.12               artist  \
0                 title   tracks     type    active_year_begin   
1                   NaN      NaN      NaN                  NaN   
2  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   
3  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   
4  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   

          artist.1           artist.2  \
0  active_year_end  associated_labels   
1              NaN                NaN   
2              NaN                NaN   
3              NaN                NaN   
4              NaN                NaN   

                                            artist.3  artist.4  \
0                                                bio  comments   
1                                                NaN       NaN   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0   
4  <p>A Way Of Life, A Collective of Hip-Hop from...         0   

              artist.5   artist.6 artist.7    artist.8    artist.9  \
0         date_created  favorites       id    latitude    location   
1                  NaN        NaN      NaN         NaN         NaN   
2  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   
3  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   
4  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   

     artist.10                                          artist.11 artist.12  \
0    longitude                                            members      name   
1          NaN                                                NaN       NaN   
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   

                                           artist.13 artist.14  \
0                                   related_projects      tags   
1                                                NaN       NaN   
2  The list of past projects is 2 long but every1...  ['awol']   
3  The list of past projects is 2 long but every1...  ['awol']   
4  The list of past projects is 2 long but every1...  ['awol']   

                                 artist.15       artist.16       set   set.1  \
0                                  website  wikipedia_page     split  subset   
1                                      NaN             NaN       NaN     NaN   
2  http://www.AzillionRecords.blogspot.com             NaN  training   small   
3  http://www.AzillionRecords.blogspot.com             NaN  training  medium   
4  http://www.AzillionRecords.blogspot.com             NaN  training   small   

      track   track.1   track.2              track.3              track.4  \
0  bit_rate  comments  composer         date_created        date_recorded   
1       NaN       NaN       NaN                  NaN                  NaN   
2    256000         0       NaN  2008-11-26 01:48:12  2008-11-26 00:00:00   
3    256000         0    

In [34]:
# headers seem to be contained in the first row of df
headers = tracks.iloc[0,:]
# track_id is in second row, fix this manually
headers[0] = 'track_id'

tracks.columns = headers
tracks.drop([0,1], axis=0, inplace=True)

In [35]:
# check data transformations
tracks.head()

0 track_id comments         date_created        date_released engineer  \
2        2        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3        3        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4        5        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
5       10        0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
6       20        0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN   

0 favorites id                                information listens producer  \
2         4  1                                    <p></p>    6073      NaN   
3         4  1                                    <p></p>    6073      NaN   
4         4  1                                    <p></p>    6073      NaN   
5         4  6                                        NaN   47632      NaN   
6         2  4  <p> "spiritual songs" from Nicky Cook</p>    2710      NaN   

0 tags                 title tracks   type    active_year_begin  \
2   []  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
3   []  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
4   []  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
5   []     Constant Hitmaker      2  Album                  NaN   
6   []                 Niris     13  Album  1990-01-01 00:00:00   

0      active_year_end                                  associated_labels  \
2                  NaN                                                NaN   
3                  NaN                                                NaN   
4                  NaN                                                NaN   
5                  NaN  Mexican Summer, Richie Records, Woodsist, Skul...   
6  2011-01-01 00:00:00                                                NaN   

0                                                bio comments  \
2  <p>A Way Of Life, A Collective of Hip-Hop from...        0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...        0   
4  <p>A Way Of Life, A Collective of Hip-Hop from...        0   
5  <p><span style="font-family:Verdana, Geneva, A...        3   
6  <p>Songs written by: Nicky Cook</p>\n<p>VOCALS...        2   

0         date_created favorites id    latitude            location  \
2  2008-11-26 01:42:32         9  1  40.0583238          New Jersey   
3  2008-11-26 01:42:32         9  1  40.0583238          New Jersey   
4  2008-11-26 01:42:32         9  1  40.0583238          New Jersey   
5  2008-11-26 01:42:55        74  6         NaN                 NaN   
6  2008-11-26 01:42:52        10  4   51.895927  Colchester England   

0    longitude                                            members        name  \
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
5          NaN                           Kurt Vile, the Violators   Kurt Vile   
6     0.891874                                       Nicky Cook\n  Nicky Cook   

0                                   related_projects  \
2  The list of past projects is 2 long but every1...   
3  The list of past projects is 2 long but every1...   
4  The list of past projects is 2 long but every1...   
5                                                NaN   
6                                                NaN   

0                                               tags  \
2                                           ['awol']   
3                                           ['awol']   
4                                           ['awol']   
5                            ['philly', 'kurt vile']   
6  ['instrumentals', 'experimental pop', 'post pu...   

0                                  website wikipedia_page     split  subset  \
2  http://www.AzillionRecords.blogspot.com            NaN  training   small   
3  http://www.AzillionRecords.blogspot.com            NaN  training  medium   
4  h

In [48]:
# cleaning up column headers, we have duplicate names for
# comments, favorites, and listens
# they may represent the same metric but for different metadata objects (e.g. artist, track, album, etc)
# album, artist, and track will be specified based on the original df column headers
headers[1] = 'comments_album'
headers[5] = 'favorites_album'
headers[8] = 'listens_album'
headers[18] = 'comments_artist'
headers[20] = 'favorites_artist'
headers[34] = 'comments_track'
headers[39] = 'favorites_track'
headers[47] = 'listens_track'

tracks.columns = headers
tracks.head()

0  track_id comments_album         date_created        date_released engineer  \
2         2              0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3         3              0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4         5              0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
5        10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
11      134              0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   

0  favorites_album id information listens_album producer tags  \
2                4  1     <p></p>          6073      NaN   []   
3                4  1     <p></p>          6073      NaN   []   
4                4  1     <p></p>          6073      NaN   []   
5                4  6         NaN         47632      NaN   []   
11               4  1     <p></p>          6073      NaN   []   

0                  title tracks   type    active_year_begin active_year_end  \
2   AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00             NaN   
3   AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00             NaN   
4   AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00             NaN   
5      Constant Hitmaker      2  Album                  NaN             NaN   
11  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00             NaN   

0                                   associated_labels  \
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
5   Mexican Summer, Richie Records, Woodsist, Skul...   
11                                                NaN   

0                                                 bio comments_artist  \
2   <p>A Way Of Life, A Collective of Hip-Hop from...               0   
3   <p>A Way Of Life, A Collective of Hip-Hop from...               0   
4   <p>A Way Of Life, A Collective of Hip-Hop from...               0   
5   <p><span style="font-family:Verdana, Geneva, A...               3   
11  <p>A Way Of Life, A Collective of Hip-Hop from...               0   

0          date_created favorites_artist id    latitude    location  \
2   2008-11-26 01:42:32                9  1  40.0583238  New Jersey   
3   2008-11-26 01:42:32                9  1  40.0583238  New Jersey   
4   2008-11-26 01:42:32                9  1  40.0583238  New Jersey   
5   2008-11-26 01:42:55               74  6         NaN         NaN   
11  2008-11-26 01:42:32                9  1  40.0583238  New Jersey   

0     longitude                                            members       name  \
2   -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
3   -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
4   -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
5           NaN                           Kurt Vile, the Violators  Kurt Vile   
11  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   

0                                    related_projects  \
2   The list of past projects is 2 long but every1...   
3   The list of past projects is 2 long but every1...   
4   The list of past projects is 2 long but every1...   
5                                                 NaN   
11  The list of past projects is 2 long but every1...   

0                      tags                                  website  \
2                  ['awol']  http://www.AzillionRecords.blogspot.com   
3                  ['awol']  http://www.AzillionRecords.blogspot.com   
4                  ['awol']  http://www.AzillionRecords.blogspot.com   
5   ['philly', 'kurt vile']                      http://kurtvile.com   
11                 ['awol']  http://www.AzillionRecords.blogspot.com   

0  wikipedia_page     split  subset bit_rate comments_track   composer  \
2             NaN  training   small   256000              0        NaN   
3             NaN  training

This is the biggest data you've played with so far, and while it does generally fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

## Resources and stretch goals

- Check out the other .csv files from the FMA dataset, and see if you can join them or otherwise fit interesting models with them
- [Logistic regression from scratch in numpy](https://blog.goodaudience.com/logistic-regression-from-scratch-in-numpy-5841c09e425f) - if you want to dig in a bit more to both the code and math (also takes a gradient descent approach, introducing the logistic loss function)
- Create a visualization to show predictions of your model - ideally show a confidence interval based on error!
- Check out and compare classification models from scikit-learn, such as [SVM](https://scikit-learn.org/stable/modules/svm.html#classification), [decision trees](https://scikit-learn.org/stable/modules/tree.html#classification), and [naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html). The underlying math will vary significantly, but the API (how you write the code) and interpretation will actually be fairly similar.
- Sign up for [Kaggle](https://kaggle.com), and find a competition to try logistic regression with
- (Not logistic regression related) If you enjoyed the assignment, you may want to read up on [music informatics](https://en.wikipedia.org/wiki/Music_informatics), which is how those audio features were actually calculated. The FMA includes the actual raw audio, so (while this is more of a longterm project than a stretch goal, and won't fit in Colab) if you'd like you can check those out and see what sort of deeper analysis you can do.

In [49]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [50]:
target = 'genre_top'

# i noticed some nulls in the target variable, let's get rid of those
tracks = tracks[tracks[target].notnull()]

Next, we will need to identify some features from the songs' metadata that are useful in predicting 'genre_top'. 

Let's try the numeric features that seem like they could be related.

In [51]:
features = ['comments_album', 'favorites_album', 'listens_album', 'comments_artist', 
            'favorites_artist', 'comments_track', 'favorites_track', 'listens_track',
           'bit_rate', 'duration', 'interest']


tracks_train = tracks[tracks['split'] == 'training']
tracks_test = tracks[tracks['split'] == 'test']

X_train, y_train = tracks_train[features], tracks_train[target]
X_test, y_test = tracks_test[features], tracks_test[target]

Alright looks like we took care of those pesky null target rows. If I was doing a more thorough analysis, I would probably take the first value from 'genres' and create a dictionary of genre ids to fill in the nulls. Perhaps another day.

In [52]:
# some quick feature scaling for faster convergence
std_scaler = StandardScaler()
X_train = std_scaler.fit_transform(X_train)
X_test = std_scaler.transform(X_test)

/Users/zach/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype object were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/zach/anaconda3/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype object were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/Users/zach/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype object were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [53]:
lr = LogisticRegression(max_iter=500, multi_class='auto', solver='lbfgs')
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=500, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [54]:
print ('Training data score: ', lr.score(X_train,y_train))
print ('Testing data score', lr.score(X_test, y_test))

Training data score:  0.4004205993540796
Testing data score 0.3851747121793577


Ehhh, not a very good score lol. Somewhat expected, given we're only using the metadata. Did we at least do better than a simple majority classifier?

In [56]:
y_test.value_counts(normalize=True)

Rock                   0.295698
Experimental           0.219148
Electronic             0.169461
Hip-Hop                0.065239
Instrumental           0.062412
Folk                   0.060392
Pop                    0.041204
International          0.025853
Classical              0.017572
Old-Time / Historic    0.011109
Jazz                   0.009493
Soul-RnB               0.008685
Spoken                 0.006261
Country                0.003636
Blues                  0.002626
Easy Listening         0.001212
Name: genre_top, dtype: float64

At least we have something that works better than a simple majority! However, it only represents ~11% improvement. Overall accuracy is pretty low.

Let's see which coefficients were most important in making predictions.

In [62]:
from sklearn.feature_selection import SelectFromModel

feat_select = SelectFromModel(lr, prefit=True)
feat_select.estimator_

AttributeError: 'SelectFromModel' object has no attribute 'estimator_'

### What are the best predictors of genre?

### What information isn't very useful in predicting genre?

### What surprised you the most about your results?