# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

In [0]:
!pip install kaggle

In [0]:
# Note - you'll also have to sign up for Kaggle and authorize the API
# https://github.com/Kaggle/kaggle-api#api-credentials

# This essentially means uploading a kaggle.json file
# For Colab we can have it in Google Drive
from google.colab import drive
drive.mount('/content/drive')
%env KAGGLE_CONFIG_DIR=/content/drive/My Drive/

# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive
env: KAGGLE_CONFIG_DIR=/content/drive/My Drive/
  0% 0.00/59.8k [00:00<?, ?B/s]
100% 59.8k/59.8k [00:00<00:00, 23.7MB/s]
  0% 0.00/28.0k [00:00<?, ?B/s]
100% 28.0k/28.0k [00:00<00:00, 28.8MB/s]
  0% 0.00/3.18k [00:00<?, ?B/s]
100% 3.18k/3.18k [00:00<00:00, 2.15MB/s]


In [0]:
# How would we try to do this with linear regression?
import pandas as pd

train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

train_df.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [0]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [0]:
from sklearn.linear_model import LinearRegression

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550917

In [0]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [0]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [0]:
import numpy as np

test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

In [0]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7103825136612022

In [0]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
log_reg.predict(test_case)[0]

1

In [0]:
help(log_reg.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.logistic.LogisticRegression instance
    Predict class labels for samples in X.
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape [n_samples]
        Predicted class label per sample.



In [0]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [0]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [0]:
log_reg.intercept_

array([1.45878264])

In [0]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
  return 1 / (1 + np.e**(-x))

In [0]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

So, clearly a more appropriate model in this situation! For more on the math, [see this Wikipedia example](https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study).

For live - let's tackle [another classification dataset on absenteeism](http://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work) - it has 21 classes, but remember, scikit-learn LogisticRegression automatically handles more than two classes. How? By essentially treating each label as different (1) from some base class (0).

In [0]:
# Live - let's try absenteeism!

## Assignment - real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

In [0]:
!wget https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
!unzip fma_metadata.zip

--2019-01-25 15:28:31--  https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
Resolving os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)... 86.119.28.13, 2001:620:5ca1:2ff::ce53
Connecting to os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)|86.119.28.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 358412441 (342M) [application/zip]
Saving to: ‘fma_metadata.zip’

fma_metadata.zip    100%[===================>] 341.81M  18.5MB/s    in 38s     

2019-01-25 15:29:11 (8.92 MB/s) - ‘fma_metadata.zip’ saved [358412441/358412441]

Archive:  fma_metadata.zip
 bunzipping: fma_metadata/README.txt  
 bunzipping: fma_metadata/checksums  
 bunzipping: fma_metadata/not_found.pickle  
 bunzipping: fma_metadata/raw_genres.csv  
 bunzipping: fma_metadata/raw_albums.csv  
 bunzipping: fma_metadata/raw_artists.csv  
 bunzipping: fma_metadata/raw_tracks.csv  
 bunzipping: fma_metadata/tracks.csv  
 bunzipping: fma_metadata/genres.csv  
 bunzipping: fma_metadata/raw_echonest.cs

In [0]:
import pandas as pd

In [0]:
tracks= pd.read_csv('fma_metadata/tracks.csv', header=[0,1], index_col=0)

In [0]:
tracks= tracks.track

In [0]:
tracks.dropna(subset=['genre_top'], how='all', inplace = True)

In [0]:
tracks.head()

bit_rate  comments   composer         date_created  \
track_id                                                       
2           256000         0        NaN  2008-11-26 01:48:12   
3           256000         0        NaN  2008-11-26 01:48:14   
5           256000         0        NaN  2008-11-26 01:48:20   
10          192000         0  Kurt Vile  2008-11-25 17:49:06   
134         256000         0        NaN  2008-11-26 01:43:19   

                date_recorded  duration  favorites genre_top genres  \
track_id                                                              
2         2008-11-26 00:00:00       168          2   Hip-Hop   [21]   
3         2008-11-26 00:00:00       237          1   Hip-Hop   [21]   
5         2008-11-26 00:00:00       206          6   Hip-Hop   [21]   
10        2008-11-26 00:00:00       161        178       Pop   [10]   
134       2008-11-26 00:00:00       207          3   Hip-Hop   [21]   

         genres_all information  interest language_code  \
track_id                                                  
2              [21]         NaN      4656            en   
3              [21]         NaN      1470            en   
5              [21]         NaN      1933            en   
10             [10]         NaN     54881            en   
134            [21]         NaN      1126            en   

                                                    license  listens lyricist  \
track_id                                                                        
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...     1293      NaN   
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...      514      NaN   
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...     1151      NaN   
10        Attribution-NonCommercial-NoDerivatives (aka M...    50135      NaN   
134       Attribution-NonCommercial-ShareAlike 3.0 Inter...      943      NaN   

          number publisher tags         title  
track_id                                       
2              3       NaN   []          Food  
3              4       NaN   []  Electric Ave  
5              6       NaN   []    This World  
10             1       NaN   []       Freeway  
134            5       NaN   []  Street Music

In [0]:
# Maybe it'd be handy to sample so we have less data so things run faster
tracks_sample = tracks.sample(5000, random_state=42)

In [0]:
tracks_sample.describe()

bit_rate    comments     duration    favorites       interest  \
count    5000.000000  5000.00000  5000.000000  5000.000000    5000.000000   
mean   261596.696000     0.02000   266.170400     2.271400    2391.493200   
std     65253.928533     0.20201   271.489538     7.280188    8495.615433   
min        -1.000000     0.00000     1.000000     0.000000       5.000000   
25%    198850.500000     0.00000   143.000000     0.000000     455.000000   
50%    256000.000000     0.00000   210.000000     1.000000     941.000000   
75%    320000.000000     0.00000   300.000000     2.000000    2028.250000   
max    448000.000000     8.00000  3682.000000   297.000000  448542.000000   

             listens       number  
count    5000.000000  5000.000000  
mean     1576.387400     8.313600  
std      5819.803875    16.549998  
min         3.000000     0.000000  
25%       211.000000     2.000000  
50%       517.000000     5.000000  
75%      1295.250000     9.000000  
max    294602.000000   255.000000

In [0]:
pd.set_option('display.max_columns', None)  # Unlimited columns
tracks_sample.head()

bit_rate  comments composer         date_created  \
track_id                                                     
152153      320000         0      NaN  2017-02-12 14:33:18   
15963       192000         0      NaN  2009-07-03 02:10:16   
20296       320000         0      NaN  2009-10-30 10:57:00   
126046      192000         0      NaN  2015-10-06 16:35:42   
1033        128000         0      NaN  2008-11-26 02:30:55   

                date_recorded  duration  favorites     genre_top  \
track_id                                                           
152153                    NaN       339          0    Electronic   
15963                     NaN       282          0    Electronic   
20296                     NaN       267         29  Experimental   
126046                    NaN        28          0          Rock   
1033      2005-01-01 00:00:00       641          0          Rock   

                  genres         genres_all information  interest  \
track_id                                                            
152153              [15]               [15]         NaN        23   
15963     [15, 181, 296]     [296, 181, 15]         NaN      2392   
20296            [1, 38]            [1, 38]         NaN     82742   
126046     [25, 85, 109]  [25, 109, 12, 85]         NaN      1611   
1033                [53]       [45, 12, 53]         NaN       413   

         language_code                                            license  \
track_id                                                                    
152153             NaN  Creative Commons Attribution-NonCommercial-NoD...   
15963               en  Attribution-NonCommercial-ShareAlike 3.0 Inter...   
20296               en  Attribution-Noncommercial-Share Alike 3.0 Unit...   
126046             NaN  Creative Commons Attribution-NonCommercial-NoD...   
1033                en  Attribution-Noncommercial-Share Alike 3.0 Unit...   

          listens lyricist  number publisher tags                    title  
track_id                                                                    
152153         19      NaN      14       NaN   []        The Divine Healer  
15963         801      NaN       4       NaN   []  The Space Bandidos (06)  
20296       68678      NaN       3       NaN   []                   Part 3  
126046       1532      NaN       6       NaN   []                        2  
1033           67      NaN       4       NaN   []                    Cut 4

In [0]:
tracks_sample = tracks_sample.reset_index()

In [0]:
tracks_sample.head()

track_id  bit_rate  comments composer         date_created  \
0    152153    320000         0      NaN  2017-02-12 14:33:18   
1     15963    192000         0      NaN  2009-07-03 02:10:16   
2     20296    320000         0      NaN  2009-10-30 10:57:00   
3    126046    192000         0      NaN  2015-10-06 16:35:42   
4      1033    128000         0      NaN  2008-11-26 02:30:55   

         date_recorded  duration  favorites     genre_top          genres  \
0                  NaN       339          0    Electronic            [15]   
1                  NaN       282          0    Electronic  [15, 181, 296]   
2                  NaN       267         29  Experimental         [1, 38]   
3                  NaN        28          0          Rock   [25, 85, 109]   
4  2005-01-01 00:00:00       641          0          Rock            [53]   

          genres_all information  interest language_code  \
0               [15]         NaN        23           NaN   
1     [296, 181, 15]         NaN      2392            en   
2            [1, 38]         NaN     82742            en   
3  [25, 109, 12, 85]         NaN      1611           NaN   
4       [45, 12, 53]         NaN       413            en   

                                             license  listens lyricist  \
0  Creative Commons Attribution-NonCommercial-NoD...       19      NaN   
1  Attribution-NonCommercial-ShareAlike 3.0 Inter...      801      NaN   
2  Attribution-Noncommercial-Share Alike 3.0 Unit...    68678      NaN   
3  Creative Commons Attribution-NonCommercial-NoD...     1532      NaN   
4  Attribution-Noncommercial-Share Alike 3.0 Unit...       67      NaN   

   number publisher tags                    title  
0      14       NaN   []        The Divine Healer  
1       4       NaN   []  The Space Bandidos (06)  
2       3       NaN   []                   Part 3  
3       6       NaN   []                        2  
4       4       NaN   []                    Cut 4

In [0]:
test_yvals= tracks_sample.genre_top

In [0]:
test_yvals.head()

0      Electronic
1      Electronic
2    Experimental
3            Rock
4            Rock
Name: genre_top, dtype: object

In [0]:
pd.options.mode.use_inf_as_na = True
tracks_sample.isna().sum()

track_id            0
bit_rate            0
comments            0
composer         4841
date_created        0
date_recorded    4616
duration            0
favorites           0
genre_top           0
genres              0
genres_all          0
information      4886
interest            0
language_code    4069
license             3
listens             0
lyricist         4986
number              0
publisher        4954
tags                0
title               0
dtype: int64

In [0]:
# While exploring, we want to be efficient and focus on what works for now
# Thanks Dan!
#garbage_columns = ['track_id','id', 'information','comments.1','title','bio',
#                  'members','website','wikipedia_page','split','subset',
#                  'comments.2','genres','genres_all','information.1','license',
 #                  'title.1']
#tracks2 = tracks.drop(columns=garbage_columns)

# Another approach, restrict columns by type
# Shreyas
numeric = ['int32', 'int64', 'float16', 'float32', 'float64']
tracks_num = tracks_sample.select_dtypes(include=numeric).copy()
tracks_sample.select_dtypes('number')
tracks_sample._get_numeric_data()  # "inner" method shorthand

# Another thing you can do - sample! See above where data loaded

track_id  bit_rate  comments  duration  favorites  interest  listens  \
0       152153    320000         0       339          0        23       19   
1        15963    192000         0       282          0      2392      801   
2        20296    320000         0       267         29     82742    68678   
3       126046    192000         0        28          0      1611     1532   
4         1033    128000         0       641          0       413       67   
5        33559    320000         0       280          1       391      230   
6        14753    256000         0       221          3       248      196   
7        37593    192000         0       156          0       915      695   
8         4088    256000         0       202          0       593      141   
9          791    256000         0       101          0       551       46   
10       29680    320000         0       350          2      1169      600   
11      116861    192000         0       199          1       837      670   
12       86798    320000         0       462          2      1839     1361   
13       93472    320000         0      1254          0       312      209   
14       32471    320000         0       255          1       192       46   
15       65475    256000         0       178          0       400      242   
16       50857    256000         0       119          1      3300     1004   
17       16524    320000         0       299          0       532      516   
18       23206    128000         0       126          0       412       49   
19       24138    128000         0       170          4      1114      324   
20       23195    128000         0       129          0       476      140   
21       99431    192000         0       103          1       100       59   
22       18223    320000         0       134          1       181      228   
23       73247    320000         0       351          0       284      124   
24      150078    320000         0       274          0       597      470   
25       65161    128000         0       144          1       436      254   
26      101948    192000         0       120          0       982      864   
27       67774    320000         0       161          1       547      212   
28      131002    320000         0       340          0       781      637   
29       28103    238354         0        96          0      1143      802   
...        ...       ...       ...       ...        ...       ...      ...   
4970    107747    192000         0       142          2       725      607   
4971    152349    320000         0       101          0       120      101   
4972     45010    192000         0      1281          0      2378      334   
4973     85691    256000         0       199          2      1843     1351   
4974    148583    265744         0       188          0       493      429   
4975    113166    320000         0       123          1     10831    10351   
4976    149681     80000         0       211          0      1215     1088   
4977     48409    192000         0        42         10     24102    15498   
4978     56594    128000         0         5          0      1042      245   
4979     44476    160000         0       203          0       791      144   
4980    149549    320000         0       247          0       143      104   
4981     96699    192000         0       245          5      3746     3481   
4982     27443    320000         0       143          4      1213      450   
4983    133566    320000         0        41          3      5976     5321   
4984     80026    320000         0       251          1       520      311   
4985     97986    320000         0       268          5      3383     2577   
4986     75204    168200         0       128          0       902      279   
4987      4255    256000         0       303          0       398      279   
4988      9174    320000         0       148          0       149       98   
4989     96698    192000    

In [0]:
tracks_sample._get_numeric_data()

track_id  bit_rate  comments  duration  favorites  interest  listens  \
0       152153    320000         0       339          0        23       19   
1        15963    192000         0       282          0      2392      801   
2        20296    320000         0       267         29     82742    68678   
3       126046    192000         0        28          0      1611     1532   
4         1033    128000         0       641          0       413       67   
5        33559    320000         0       280          1       391      230   
6        14753    256000         0       221          3       248      196   
7        37593    192000         0       156          0       915      695   
8         4088    256000         0       202          0       593      141   
9          791    256000         0       101          0       551       46   
10       29680    320000         0       350          2      1169      600   
11      116861    192000         0       199          1       837      670   
12       86798    320000         0       462          2      1839     1361   
13       93472    320000         0      1254          0       312      209   
14       32471    320000         0       255          1       192       46   
15       65475    256000         0       178          0       400      242   
16       50857    256000         0       119          1      3300     1004   
17       16524    320000         0       299          0       532      516   
18       23206    128000         0       126          0       412       49   
19       24138    128000         0       170          4      1114      324   
20       23195    128000         0       129          0       476      140   
21       99431    192000         0       103          1       100       59   
22       18223    320000         0       134          1       181      228   
23       73247    320000         0       351          0       284      124   
24      150078    320000         0       274          0       597      470   
25       65161    128000         0       144          1       436      254   
26      101948    192000         0       120          0       982      864   
27       67774    320000         0       161          1       547      212   
28      131002    320000         0       340          0       781      637   
29       28103    238354         0        96          0      1143      802   
...        ...       ...       ...       ...        ...       ...      ...   
4970    107747    192000         0       142          2       725      607   
4971    152349    320000         0       101          0       120      101   
4972     45010    192000         0      1281          0      2378      334   
4973     85691    256000         0       199          2      1843     1351   
4974    148583    265744         0       188          0       493      429   
4975    113166    320000         0       123          1     10831    10351   
4976    149681     80000         0       211          0      1215     1088   
4977     48409    192000         0        42         10     24102    15498   
4978     56594    128000         0         5          0      1042      245   
4979     44476    160000         0       203          0       791      144   
4980    149549    320000         0       247          0       143      104   
4981     96699    192000         0       245          5      3746     3481   
4982     27443    320000         0       143          4      1213      450   
4983    133566    320000         0        41          3      5976     5321   
4984     80026    320000         0       251          1       520      311   
4985     97986    320000         0       268          5      3383     2577   
4986     75204    168200         0       128          0       902      279   
4987      4255    256000         0       303          0       398      279   
4988      9174    320000         0       148          0       149       98   
4989     96698    192000    

In [0]:
tracks.shape

(49598, 20)

This is the biggest data you've played with so far, and while it does generally fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

In [0]:
sample = tracks_sample._get_numeric_data()

In [0]:
sample.head()

track_id  bit_rate  comments  duration  favorites  interest  listens  \
0    152153    320000         0       339          0        23       19   
1     15963    192000         0       282          0      2392      801   
2     20296    320000         0       267         29     82742    68678   
3    126046    192000         0        28          0      1611     1532   
4      1033    128000         0       641          0       413       67   

   number  
0      14  
1       4  
2       3  
3       6  
4       4

In [0]:
sample.shape

(5000, 8)

In [0]:
sample.head()

track_id  bit_rate  comments  duration  favorites  interest  listens  \
0    152153    320000         0       339          0        23       19   
1     15963    192000         0       282          0      2392      801   
2     20296    320000         0       267         29     82742    68678   
3    126046    192000         0        28          0      1611     1532   
4      1033    128000         0       641          0       413       67   

   number  
0      14  
1       4  
2       3  
3       6  
4       4

In [1]:
from sklearn.linear_model import LogisticRegression
import numpy as np



X = sample
y = test_yvals

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

NameError: ignored