# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

In [1]:
!pip install kaggle

In [2]:
# Note - you'll also have to sign up for Kaggle and authorize the API
# https://github.com/Kaggle/kaggle-api#api-credentials

# This essentially means uploading a kaggle.json file
# For Colab we can have it in Google Drive
# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

train.csv: Skipping, found more recently modified local copy (use --force to force download)
test.csv: Skipping, found more recently modified local copy (use --force to force download)
gender_submission.csv: Skipping, found more recently modified local copy (use --force to force download)


In [3]:
# How would we try to do this with linear regression?
import pandas as pd

train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

train_df.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [4]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [5]:
from sklearn.linear_model import LinearRegression

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550906

In [6]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [7]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [8]:
import numpy as np

test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

In [9]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

/Users/chrislouie/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7103825136612022

In [10]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
log_reg.predict(test_case)[0]

1

In [12]:
help(log_reg.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.logistic.LogisticRegression instance
    Predict class labels for samples in X.
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape [n_samples]
        Predicted class label per sample.



In [13]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [14]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [15]:
log_reg.intercept_

array([1.45878264])

In [16]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
    return 1 / (1 + np.e**(-x))

In [17]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

So, clearly a more appropriate model in this situation! For more on the math, [see this Wikipedia example](https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study).

For live - let's tackle [another classification dataset on absenteeism](http://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work) - it has 21 classes, but remember, scikit-learn LogisticRegression automatically handles more than two classes. How? By essentially treating each label as different (1) from some base class (0).

In [18]:
# Live - let's try absenteeism!

## Assignment - real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

In [19]:
# !wget https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
# !unzip fma_metadata.zip.1

In [20]:
!7za x fma_metadata.zip.1 S


7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
  0M Scan         1 file, 358412441 bytes (342 MiB)

Extracting archive: fma_metadata.zip.1
--
Path = fma_metadata.zip.1
Type = zip
Physical Size = 358412441


No files to process
Everything is Ok

Files: 0
Size:       0
Compressed: 358412441


In [21]:
tracks = pd.read_csv('fma_metadata/tracks.csv')

/Users/chrislouie/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,1,5,6,8,12,18,20,21,22,24,33,34,38,39,44,47,49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [22]:
tracks.describe()

Unnamed: 0   album              album.1              album.2  \
count      106575  106575               103046                70295   
unique     106575      29                14341                 3670   
top         23458       0  2015-01-26 13:04:57  2008-01-01 00:00:00   
freq            1   71187                  310                  667   

               album.3  album.4  album.5  \
count            15296   106575   106575   
unique             623       65    14929   
top     Ernie Indradat        0       -1   
freq               876    45753      805   

                                                  album.6  album.7  \
count                                               83150   106575   
unique                                              11076    11351   
top     <p class="p1" style="margin: 0px; padding: 8px...       -1   
freq                                                  310     3130   

           album.8    ...     \
count        18061    ...      
unique         761    ...      
top     Joe Belock    ...      
freq           855    ...      

                                                 track.10 track.11  track.12  \
count                                                2350   106575     15025   
unique                                               1587    18977        45   
top     <p><a href="http://www.myspace.com/theshambler...      320        en   
freq                                                   22       67     14255   

                                                 track.13 track.14  \
count                                              106488   106575   
unique                                                114    15340   
top     Attribution-Noncommercial-Share Alike 3.0 Unit...       97   
freq                                                19250      110   

             track.15 track.16              track.17  track.18  track.19  
count             312   106575                  1264    106575    106574  
unique             67      331                   136      2452     94987  
top     Apache Tomcat        1  Victrola Dog (ASCAP)        []  Untitled  
freq               44    10459                   465     83078       298  

[4 rows x 53 columns]

In [23]:
pd.set_option('display.max_columns', None)  # Unlimited columns
tracks.head()

Unnamed: 0     album              album.1              album.2   album.3  \
0        NaN  comments         date_created        date_released  engineer   
1   track_id       NaN                  NaN                  NaN       NaN   
2          2         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
3          3         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
4          5         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   

     album.4 album.5      album.6  album.7   album.8 album.9  \
0  favorites      id  information  listens  producer    tags   
1        NaN     NaN          NaN      NaN       NaN     NaN   
2          4       1      <p></p>     6073       NaN      []   
3          4       1      <p></p>     6073       NaN      []   
4          4       1      <p></p>     6073       NaN      []   

               album.10 album.11 album.12               artist  \
0                 title   tracks     type    active_year_begin   
1                   NaN      NaN      NaN                  NaN   
2  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   
3  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   
4  AWOL - A Way Of Life        7    Album  2006-01-01 00:00:00   

          artist.1           artist.2  \
0  active_year_end  associated_labels   
1              NaN                NaN   
2              NaN                NaN   
3              NaN                NaN   
4              NaN                NaN   

                                            artist.3  artist.4  \
0                                                bio  comments   
1                                                NaN       NaN   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0   
4  <p>A Way Of Life, A Collective of Hip-Hop from...         0   

              artist.5   artist.6 artist.7    artist.8    artist.9  \
0         date_created  favorites       id    latitude    location   
1                  NaN        NaN      NaN         NaN         NaN   
2  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   
3  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   
4  2008-11-26 01:42:32          9        1  40.0583238  New Jersey   

     artist.10                                          artist.11 artist.12  \
0    longitude                                            members      name   
1          NaN                                                NaN       NaN   
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...      AWOL   

                                           artist.13 artist.14  \
0                                   related_projects      tags   
1                                                NaN       NaN   
2  The list of past projects is 2 long but every1...  ['awol']   
3  The list of past projects is 2 long but every1...  ['awol']   
4  The list of past projects is 2 long but every1...  ['awol']   

                                 artist.15       artist.16       set   set.1  \
0                                  website  wikipedia_page     split  subset   
1                                      NaN             NaN       NaN     NaN   
2  http://www.AzillionRecords.blogspot.com             NaN  training   small   
3  http://www.AzillionRecords.blogspot.com             NaN  training  medium   
4  http://www.AzillionRecords.blogspot.com             NaN  training   small   

      track   track.1   track.2              track.3              track.4  \
0  bit_rate  comments  composer         date_created        date_recorded   
1       NaN       NaN       NaN                  NaN                  NaN   
2    256000         0       NaN  2008-11-26 01:48:12  2008-11-26 00:00:00   
3    256000         0    

In [24]:
tracks.shape

(106576, 53)

This is the biggest data you've played with so far, and while it does generally fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

In [25]:
tracks.columns

Index(['Unnamed: 0', 'album', 'album.1', 'album.2', 'album.3', 'album.4',
       'album.5', 'album.6', 'album.7', 'album.8', 'album.9', 'album.10',
       'album.11', 'album.12', 'artist', 'artist.1', 'artist.2', 'artist.3',
       'artist.4', 'artist.5', 'artist.6', 'artist.7', 'artist.8', 'artist.9',
       'artist.10', 'artist.11', 'artist.12', 'artist.13', 'artist.14',
       'artist.15', 'artist.16', 'set', 'set.1', 'track', 'track.1', 'track.2',
       'track.3', 'track.4', 'track.5', 'track.6', 'track.7', 'track.8',
       'track.9', 'track.10', 'track.11', 'track.12', 'track.13', 'track.14',
       'track.15', 'track.16', 'track.17', 'track.18', 'track.19'],
      dtype='object')

In [26]:
tracks = tracks.rename(columns={'Unnamed: 0': 'track_id'})

renamed_cols = {
    'album': 'alb_comments',
    'album.1': 'alb_date_created',
    'album.2': 'alb_date_released',
    'album.3': 'engineer',
    'album.4': 'alb_favorites',
    'album.5': 'alb_id',
    'album.6': 'alb_information',
    'album.7': 'alb_listens',
    'album.8': 'alb_producer',
    'album.9': 'alb_tags',
    'album.10': 'alb_title',
    'album.11': 'alb_tracks',
    'album.12': 'alb_type',
    'artist': 'active_year_begin',
    'artist.1': 'active_year_end',
    'artist.2': 'associated_labels',
    'artist.3': 'art_bio',
    'artist.4': 'art_comments',
    'artist.5': 'art_date_created', 
    'artist.6': 'art_favorites',
    'artist.7': 'art_id',
    'artist.8': 'latitude',
    'artist.9': 'location',
    'artist.10': 'longitude',
    'artist.11': 'members', 
    'artist.12': 'name', 
    'artist.13': 'related_projects', 
    'artist.14': 'tags',
    'artist.15': 'website', 
    'artist.16': 'wikipedia_page', 
    'set': 'split', 
    'set.1': 'subset', 
    'track': 'bitrate', 
    'track.1': 'track_comments', 
    'track.2': 'composer',
    'track.3': 'track_date_created', 
    'track.4': 'track_date_recorded', 
    'track.5': 'duration', 
    'track.6': 'favorites', 
    'track.7': 'genre_top', 
    'track.8': 'genres',
    'track.9': 'genres_all', 
    'track.10': 'track_information', 
    'track.11': 'interest', 
    'track.12': 'language_code', 
    'track.13': 'license', 
    'track.14': 'track_listens',
    'track.15': 'lyricist', 
    'track.16': 'number', 
    'track.17': 'publisher', 
    'track.18': 'track_tags', 
    'track.19': 'track_title'
    
}

tracks = tracks.rename(columns=renamed_cols)


In [27]:
tracks.head()

track_id alb_comments     alb_date_created    alb_date_released  engineer  \
0       NaN     comments         date_created        date_released  engineer   
1  track_id          NaN                  NaN                  NaN       NaN   
2         2            0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
3         3            0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
4         5            0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   

  alb_favorites alb_id alb_information alb_listens alb_producer alb_tags  \
0     favorites     id     information     listens     producer     tags   
1           NaN    NaN             NaN         NaN          NaN      NaN   
2             4      1         <p></p>        6073          NaN       []   
3             4      1         <p></p>        6073          NaN       []   
4             4      1         <p></p>        6073          NaN       []   

              alb_title alb_tracks alb_type    active_year_begin  \
0                 title     tracks     type    active_year_begin   
1                   NaN        NaN      NaN                  NaN   
2  AWOL - A Way Of Life          7    Album  2006-01-01 00:00:00   
3  AWOL - A Way Of Life          7    Album  2006-01-01 00:00:00   
4  AWOL - A Way Of Life          7    Album  2006-01-01 00:00:00   

   active_year_end  associated_labels  \
0  active_year_end  associated_labels   
1              NaN                NaN   
2              NaN                NaN   
3              NaN                NaN   
4              NaN                NaN   

                                             art_bio art_comments  \
0                                                bio     comments   
1                                                NaN          NaN   
2  <p>A Way Of Life, A Collective of Hip-Hop from...            0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...            0   
4  <p>A Way Of Life, A Collective of Hip-Hop from...            0   

      art_date_created art_favorites art_id    latitude    location  \
0         date_created     favorites     id    latitude    location   
1                  NaN           NaN    NaN         NaN         NaN   
2  2008-11-26 01:42:32             9      1  40.0583238  New Jersey   
3  2008-11-26 01:42:32             9      1  40.0583238  New Jersey   
4  2008-11-26 01:42:32             9      1  40.0583238  New Jersey   

     longitude                                            members  name  \
0    longitude                                            members  name   
1          NaN                                                NaN   NaN   
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...  AWOL   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...  AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...  AWOL   

                                    related_projects      tags  \
0                                   related_projects      tags   
1                                                NaN       NaN   
2  The list of past projects is 2 long but every1...  ['awol']   
3  The list of past projects is 2 long but every1...  ['awol']   
4  The list of past projects is 2 long but every1...  ['awol']   

                                   website  wikipedia_page     split  subset  \
0                                  website  wikipedia_page     split  subset   
1                                      NaN             NaN       NaN     NaN   
2  http://www.AzillionRecords.blogspot.com             NaN  training   small   
3  http://www.AzillionRecords.blogspot.com             NaN  training  medium   
4  http://www.AzillionRecords.blogspot.com             NaN  training   small   

    bitrate track_comments  composer   track_date_created  \
0  bit_rate       comments  composer         date_created   
1       NaN            NaN       NaN                  NaN   
2    256000              0       NaN  2008-11-26 01:48:

In [28]:
tracks = tracks.iloc[2:]
tracks.head()

track_id alb_comments     alb_date_created    alb_date_released engineer  \
2        2            0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3        3            0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4        5            0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
5       10            0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
6       20            0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN   

  alb_favorites alb_id                            alb_information alb_listens  \
2             4      1                                    <p></p>        6073   
3             4      1                                    <p></p>        6073   
4             4      1                                    <p></p>        6073   
5             4      6                                        NaN       47632   
6             2      4  <p> "spiritual songs" from Nicky Cook</p>        2710   

  alb_producer alb_tags             alb_title alb_tracks alb_type  \
2          NaN       []  AWOL - A Way Of Life          7    Album   
3          NaN       []  AWOL - A Way Of Life          7    Album   
4          NaN       []  AWOL - A Way Of Life          7    Album   
5          NaN       []     Constant Hitmaker          2    Album   
6          NaN       []                 Niris         13    Album   

     active_year_begin      active_year_end  \
2  2006-01-01 00:00:00                  NaN   
3  2006-01-01 00:00:00                  NaN   
4  2006-01-01 00:00:00                  NaN   
5                  NaN                  NaN   
6  1990-01-01 00:00:00  2011-01-01 00:00:00   

                                   associated_labels  \
2                                                NaN   
3                                                NaN   
4                                                NaN   
5  Mexican Summer, Richie Records, Woodsist, Skul...   
6                                                NaN   

                                             art_bio art_comments  \
2  <p>A Way Of Life, A Collective of Hip-Hop from...            0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...            0   
4  <p>A Way Of Life, A Collective of Hip-Hop from...            0   
5  <p><span style="font-family:Verdana, Geneva, A...            3   
6  <p>Songs written by: Nicky Cook</p>\n<p>VOCALS...            2   

      art_date_created art_favorites art_id    latitude            location  \
2  2008-11-26 01:42:32             9      1  40.0583238          New Jersey   
3  2008-11-26 01:42:32             9      1  40.0583238          New Jersey   
4  2008-11-26 01:42:32             9      1  40.0583238          New Jersey   
5  2008-11-26 01:42:55            74      6         NaN                 NaN   
6  2008-11-26 01:42:52            10      4   51.895927  Colchester England   

     longitude                                            members        name  \
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
5          NaN                           Kurt Vile, the Violators   Kurt Vile   
6     0.891874                                       Nicky Cook\n  Nicky Cook   

                                    related_projects  \
2  The list of past projects is 2 long but every1...   
3  The list of past projects is 2 long but every1...   
4  The list of past projects is 2 long but every1...   
5                                                NaN   
6                                                NaN   

                                                tags  \
2                                           ['awol']   
3                                           ['awol']   
4                                           ['awol']   
5                            ['philly', 'kurt vile']   
6  ['instrumental

In [29]:
tracks.isna().sum()

track_id                    0
alb_comments                0
alb_date_created         3529
alb_date_released       36280
engineer                91279
alb_favorites               0
alb_id                      0
alb_information         23425
alb_listens                 0
alb_producer            88514
alb_tags                    0
alb_title                1025
alb_tracks                  0
alb_type                 6508
active_year_begin       83863
active_year_end        101199
associated_labels       92303
art_bio                 35418
art_comments                0
art_date_created          856
art_favorites               0
art_id                      0
latitude                62030
location                36364
longitude               62030
members                 59725
name                        0
related_projects        93422
tags                        0
website                 27318
wikipedia_page         100993
split                       0
subset                      0
bitrate   

In [30]:
df = tracks.drop(columns={
    'engineer',
    'associated_labels',
    'active_year_begin',
    'active_year_end',
    'composer',
    'track_information',
    'lyricist',
    'publisher',
    'track_date_recorded',
    'wikipedia_page',
    'related_projects',
    'language_code'
})
df.isna().sum()

track_id                  0
alb_comments              0
alb_date_created       3529
alb_date_released     36280
alb_favorites             0
alb_id                    0
alb_information       23425
alb_listens               0
alb_producer          88514
alb_tags                  0
alb_title              1025
alb_tracks                0
alb_type               6508
art_bio               35418
art_comments              0
art_date_created        856
art_favorites             0
art_id                    0
latitude              62030
location              36364
longitude             62030
members               59725
name                      0
tags                      0
website               27318
split                     0
subset                    0
bitrate                   0
track_comments            0
track_date_created        0
duration                  0
favorites                 0
genre_top             56976
genres                    0
genres_all                0
interest            

In [31]:
def sigmoid(x):
    return 1/(1+np.e**(-x))

In [32]:
X = tracks[['interest','bitrate','duration']]
y = tracks['track_listens']

linear_reg = LinearRegression().fit(X,y)
linear_reg.score(X,y)

0.6953462888558701

In [33]:
linear_reg.coef_

array([ 0.35185483,  0.00154688, -0.22168127])

In [34]:
linear_reg.intercept_

737.6672000704316

In [35]:
# y = y.astype(int)
# log_reg = LogisticRegression().fit(X,y)
# log_reg.score(X,y)

In [36]:
X = tracks[['interest','bitrate','duration']].astype(int).values
y = tracks['track_listens'].astype(int).values

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
from sklearn.linear_model.logistic import LogisticRegression

In [40]:
?LogisticRegression

In [39]:
tracks.columns

Index(['track_id', 'alb_comments', 'alb_date_created', 'alb_date_released',
       'engineer', 'alb_favorites', 'alb_id', 'alb_information', 'alb_listens',
       'alb_producer', 'alb_tags', 'alb_title', 'alb_tracks', 'alb_type',
       'active_year_begin', 'active_year_end', 'associated_labels', 'art_bio',
       'art_comments', 'art_date_created', 'art_favorites', 'art_id',
       'latitude', 'location', 'longitude', 'members', 'name',
       'related_projects', 'tags', 'website', 'wikipedia_page', 'split',
       'subset', 'bitrate', 'track_comments', 'composer', 'track_date_created',
       'track_date_recorded', 'duration', 'favorites', 'genre_top', 'genres',
       'genres_all', 'track_information', 'interest', 'language_code',
       'license', 'track_listens', 'lyricist', 'number', 'publisher',
       'track_tags', 'track_title'],
      dtype='object')

In [40]:
tracks.isna().sum()

track_id                    0
alb_comments                0
alb_date_created         3529
alb_date_released       36280
engineer                91279
alb_favorites               0
alb_id                      0
alb_information         23425
alb_listens                 0
alb_producer            88514
alb_tags                    0
alb_title                1025
alb_tracks                  0
alb_type                 6508
active_year_begin       83863
active_year_end        101199
associated_labels       92303
art_bio                 35418
art_comments                0
art_date_created          856
art_favorites               0
art_id                      0
latitude                62030
location                36364
longitude               62030
members                 59725
name                        0
related_projects        93422
tags                        0
website                 27318
wikipedia_page         100993
split                       0
subset                      0
bitrate   

In [41]:
X = tracks[['track_listens', 'art_comments', 'track_comments', 'alb_comments']]
y = tracks['genres']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,y,test_size=.2,random_state=42)

model = LogisticRegression(random_state=42, solver='lbfgs', multi_class='multinomial', max_iter=1000)
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

In [ ]:
# model = LogisticRegression(random_state=42, solver='lbfgs', multi_class='multinomial', max_iter = 1000)
# model.fit(X,y)
# model.score(X,y)

## Resources and stretch goals

- Check out the other .csv files from the FMA dataset, and see if you can join them or otherwise fit interesting models with them
- [Logistic regression from scratch in numpy](https://blog.goodaudience.com/logistic-regression-from-scratch-in-numpy-5841c09e425f) - if you want to dig in a bit more to both the code and math (also takes a gradient descent approach, introducing the logistic loss function)
- Create a visualization to show predictions of your model - ideally show a confidence interval based on error!
- Check out and compare classification models from scikit-learn, such as [SVM](https://scikit-learn.org/stable/modules/svm.html#classification), [decision trees](https://scikit-learn.org/stable/modules/tree.html#classification), and [naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html). The underlying math will vary significantly, but the API (how you write the code) and interpretation will actually be fairly similar.
- Sign up for [Kaggle](https://kaggle.com), and find a competition to try logistic regression with
- (Not logistic regression related) If you enjoyed the assignment, you may want to read up on [music informatics](https://en.wikipedia.org/wiki/Music_informatics), which is how those audio features were actually calculated. The FMA includes the actual raw audio, so (while this is more of a longterm project than a stretch goal, and won't fit in Colab) if you'd like you can check those out and see what sort of deeper analysis you can do.