# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

In [0]:
#Logistic models are CLASSIFICATION models
#can predict non-continuous outputs
#passes function through second Sigmoid function to give a (0,1) range to output
#predict precentages, probabilities, bools, classes
#x var, y var - features and labels

![logistic regression](https://www.totalprosports.com/wp-content/uploads/2016/03/horse-wearing-a-three-piece-suit-2.jpg)

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

In [1]:
!pip install kaggle

In [19]:
# Note - you'll also have to sign up for Kaggle and authorize the API
# https://github.com/Kaggle/kaggle-api#api-credentials

# This essentially means uploading a kaggle.json file
# For Colab we can have it in Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
%env KAGGLE_CONFIG_DIR=/content/drive/My Drive/
# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

Mounted at /content/drive
env: KAGGLE_CONFIG_DIR=/content/drive/My Drive/
  0% 0.00/59.8k [00:00<?, ?B/s]
100% 59.8k/59.8k [00:00<00:00, 53.1MB/s]
  0% 0.00/28.0k [00:00<?, ?B/s]
100% 28.0k/28.0k [00:00<00:00, 26.9MB/s]
  0% 0.00/3.18k [00:00<?, ?B/s]
100% 3.18k/3.18k [00:00<00:00, 2.69MB/s]


In [20]:
# How would we try to do this with linear regression?
import pandas as pd

train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

train_df.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

In [21]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [26]:
#Linear regression predicting survival depending on class, age, fare
from sklearn.linear_model import LinearRegression

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550917

In [27]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [28]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [29]:
#how well does this predict?
#gives percentages over 100%
import numpy as np

test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

In [30]:
#logistic regression with same conditions
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7103825136612022

In [31]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
log_reg.predict(test_case)[0]

1

In [33]:
help(log_reg.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.logistic.LogisticRegression instance
    Predict class labels for samples in X.
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape [n_samples]
        Predicted class label per sample.



In [34]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [35]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [36]:
log_reg.intercept_

array([1.45878264])

In [0]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
  return 1 / (1 + np.e**(-x))

In [38]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

So, clearly a more appropriate model in this situation! For more on the math, [see this Wikipedia example](https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study).

For live - let's tackle [another classification dataset on absenteeism](http://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work) - it has 21 classes, but remember, scikit-learn LogisticRegression automatically handles more than two classes. How? By essentially treating each label as different (1) from some base class (0).

In [39]:
# Live - let's try absenteeism!
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/00445/Absenteeism_at_work_AAA.zip
!unzip Absenteeism_at_work_AAA.zip

--2019-02-25 18:19:34--  http://archive.ics.uci.edu/ml/machine-learning-databases/00445/Absenteeism_at_work_AAA.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66136 (65K) [application/zip]
Saving to: ‘Absenteeism_at_work_AAA.zip’

Absenteeism_at_work 100%[===================>]  64.59K   179KB/s    in 0.4s    

2019-02-25 18:19:34 (179 KB/s) - ‘Absenteeism_at_work_AAA.zip’ saved [66136/66136]

Archive:  Absenteeism_at_work_AAA.zip
  inflating: Absenteeism_at_work.arff  
  inflating: Absenteeism_at_work.csv  
  inflating: Absenteeism_at_work.xls  
  inflating: Attribute Information.docx  
  inflating: UCI_ABS_TEXT.docx       


In [40]:
!head Absenteeism_at_work.csv
#mislabelled - semi seperated

ID;Reason for absence;Month of absence;Day of the week;Seasons;Transportation expense;Distance from Residence to Work;Service time;Age;Work load Average/day ;Hit target;Disciplinary failure;Education;Son;Social drinker;Social smoker;Pet;Weight;Height;Body mass index;Absenteeism time in hours
11;26;7;3;1;289;36;13;33;239.554;97;0;1;2;1;0;1;90;172;30;4
36;0;7;3;1;118;13;18;50;239.554;97;1;1;1;1;0;0;98;178;31;0
3;23;7;4;1;179;51;18;38;239.554;97;0;1;0;1;0;0;89;170;31;2
7;7;7;5;1;279;5;14;39;239.554;97;0;1;2;1;1;0;68;168;24;4
11;23;7;5;1;289;36;13;33;239.554;97;0;1;2;1;0;1;90;172;30;2
3;23;7;6;1;179;51;18;38;239.554;97;0;1;0;1;0;0;89;170;31;2
10;22;7;6;1;361;52;3;28;239.554;97;0;1;1;1;0;4;80;172;27;8
20;23;7;6;1;260;50;11;36;239.554;97;0;1;4;1;0;0;65;168;23;4
14;19;7;2;1;155;12;14;34;239.554;97;0;1;2;1;0;0;95;196;25;40


In [42]:
pd.set_option('display.max_columns', 50)
df = pd.read_csv('Absenteeism_at_work.csv', sep=';')
df.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   Hit target  Disciplinary failure  Education  Son  \
0                 239.554          97                     0          1    2   
1                 239.554          97                     1          1    1   
2                 239.554          97                     0          1    0   
3                 239.554          97                     0          1    2   
4                 239.554          97                     0          1    2   

   Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0               1              0    1      90     172               30   
1               1              0    0      98     178               31   
2               1              0    0      89     170               31   
3               1              1    0      68     168               24   
4               1              0    1      90     172               30   

   Absenteeism time in hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [46]:
df['Reason for absence'].value_counts()
#categorical variable
#classes of types of absence

23    149
28    112
27     69
13     55
0      43
19     40
22     38
26     33
25     31
11     26
10     25
18     21
14     19
1      16
7      15
6       8
12      8
8       6
21      6
9       4
5       3
24      3
16      3
4       2
15      2
3       1
2       1
17      1
Name: Reason for absence, dtype: int64

In [47]:
df['Absenteeism time in hours'].value_counts()
#not a categorical variable
#its distribution is continuous

8      208
2      157
3      112
1       88
4       60
0       44
16      19
24      16
40       7
5        7
32       6
64       3
80       3
120      3
112      2
56       2
48       1
7        1
104      1
Name: Absenteeism time in hours, dtype: int64

In [0]:
X = df.drop(columns = ['ID', 'Reason for absence'])
y = df['Reason for absence']

In [62]:
from sklearn.linear_model.logistic import LogisticRegression
model = LogisticRegression(random_state=42, solver = 'lbfgs',
                           multi_class = 'multinomial', max_iter=10000)
model.fit(X,y)
model.score(X,y) #50% likely to fit in right class
#warnings: specify solver and multiclass
#this way model is optimized to be multinomial and use grad descent
#warnings: no min (didn't converge) when solver = lbfgs
#change num of iterations

0.5121621621621621

In [63]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X,y,test_size=0.2, random_state=42)

model2 = LogisticRegression(random_state=42, solver = 'lbfgs',
                           multi_class = 'multinomial', max_iter=8000)

model2.fit(Xtrain, ytrain)
model2.score(Xtest, ytest)
#we are looking for score. Don't worry.
#the low score for a badly formulated question like predicting health conditions
#is reassuring, really

0.3716216216216216

In [64]:
predictions = model2.predict(Xtest)
predictions

array([27, 23, 15, 23, 27, 23, 23, 13, 22, 28,  0,  0, 23, 13,  0,  1, 23,
       23, 14, 28, 22, 23, 13,  0, 23, 28, 28, 27, 23, 13, 24, 23, 24, 28,
       23, 28, 23, 23, 13, 19, 22, 22, 22, 28, 23, 27, 26, 19, 23, 23, 27,
       18, 23, 28, 25,  0, 28,  0, 21, 19, 11, 28, 13,  7, 26, 19, 23, 28,
       27, 13, 27, 22, 13, 16, 23, 10, 23, 27, 10, 10, 28, 23, 13, 22, 22,
       27, 28, 18, 22, 10, 28,  0, 23, 28, 23, 27, 23, 10, 27, 11, 23,  7,
       14, 23, 27, 27, 22, 27,  0, 27, 26, 25, 28, 28, 13, 10, 27, 23, 14,
       19, 23, 23, 26, 28, 27, 23,  0, 23, 22, 23, 27, 23, 27, 28,  5, 18,
       26, 23, 23, 23, 23, 28, 19, 23, 27, 27, 23, 23])

In [65]:
from collections import Counter
Counter(predictions)

Counter({0: 9,
         1: 1,
         5: 1,
         7: 2,
         10: 6,
         11: 2,
         13: 10,
         14: 3,
         15: 1,
         16: 1,
         18: 3,
         19: 6,
         21: 1,
         22: 11,
         23: 41,
         24: 2,
         25: 2,
         26: 5,
         27: 21,
         28: 20})

In [67]:
#test case
#import numpy as np
one_row = np.array(Xtest.iloc[0])
one_row

array([  1.   ,   6.   ,   2.   , 225.   ,  26.   ,   9.   ,  28.   ,
       308.593,  95.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,
         2.   ,  69.   , 169.   ,  24.   ,   1.   ])

In [68]:
print(model2.predict(one_row.reshape(1,-1)))
#same as first value in full predictions array

[27]


## Assignment - real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

In [0]:
#Assignment - metadata from music tracks extracted from wav
#need to clean - might need to directly edit csv
#predict genre from metadata
#what are the best predictors for genre?
#what isn't useful for predicting genre?
#what surprised me about predictions?

In [88]:
!wget https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
!unzip fma_metadata.zip

--2019-02-25 20:55:44--  https://os.unil.cloud.switch.ch/fma/fma_metadata.zip
Resolving os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)... 86.119.28.13, 2001:620:5ca1:2ff::ce53
Connecting to os.unil.cloud.switch.ch (os.unil.cloud.switch.ch)|86.119.28.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 358412441 (342M) [application/zip]
Saving to: ‘fma_metadata.zip.1’

fma_metadata.zip.1  100%[===================>] 341.81M  24.4MB/s    in 15s     

2019-02-25 20:56:00 (22.7 MB/s) - ‘fma_metadata.zip.1’ saved [358412441/358412441]

Archive:  fma_metadata.zip
replace fma_metadata/README.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace fma_metadata/checksums? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
 bunzipping: fma_metadata/checksums  
replace fma_metadata/not_found.pickle? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
 bunzipping: fma_metadata/not_found.pickle  
replace fma_metadata/raw_genres.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [91]:
tracks = pd.read_csv('fma_metadata/tracks.csv', names=tracks.iloc[1]) #mixed type warning

/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py:709: UserWarning: Duplicate names specified. This will raise an error in the future.
  return _read(filepath_or_buffer, kwds)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,5,6,8,12,18,20,21,22,24,33,34,38,39,44,47,49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [92]:
tracks.head()

NaN  comments         date_created        date_released  engineer  \
0       NaN     album                album                album     album   
1       NaN  comments         date_created        date_released  engineer   
2  track_id       NaN                  NaN                  NaN       NaN   
3         2         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   
4         3         0  2008-11-26 01:44:45  2009-01-05 00:00:00       NaN   

   favorites     id  information  listens  producer   tags  \
0      album  album        album    album     album  album   
1  favorites     id  information  listens  producer   tags   
2        NaN    NaN          NaN      NaN       NaN    NaN   
3          4      1      <p></p>     6073       NaN     []   
4          4      1      <p></p>     6073       NaN     []   

                  title  tracks   type    active_year_begin  active_year_end  \
0                 album   album  album               artist           artist   
1                 title  tracks   type    active_year_begin  active_year_end   
2                   NaN     NaN    NaN                  NaN              NaN   
3  AWOL - A Way Of Life       7  Album  2006-01-01 00:00:00              NaN   
4  AWOL - A Way Of Life       7  Album  2006-01-01 00:00:00              NaN   

   associated_labels                                                bio  \
0             artist                                             artist   
1  associated_labels                                                bio   
2                NaN                                                NaN   
3                NaN  <p>A Way Of Life, A Collective of Hip-Hop from...   
4                NaN  <p>A Way Of Life, A Collective of Hip-Hop from...   

  comments.1       date_created.1 favorites.1    id.1    latitude    location  \
0     artist               artist      artist  artist      artist      artist   
1   comments         date_created   favorites      id    latitude    location   
2        NaN                  NaN         NaN     NaN         NaN         NaN   
3          0  2008-11-26 01:42:32           9       1  40.0583238  New Jersey   
4          0  2008-11-26 01:42:32           9       1  40.0583238  New Jersey   

     longitude                                            members    name  \
0       artist                                             artist  artist   
1    longitude                                            members    name   
2          NaN                                                NaN     NaN   
3  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...    AWOL   
4  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...    AWOL   

                                    related_projects    tags.1  \
0                                             artist    artist   
1                                   related_projects      tags   
2                                                NaN       NaN   
3  The list of past projects is 2 long but every1...  ['awol']   
4  The list of past projects is 2 long but every1...  ['awol']   

                                   website  wikipedia_page     split  subset  \
0                                   artist          artist       set     set   
1                                  website  wikipedia_page     split  subset   
2                                      NaN             NaN       NaN     NaN   
3  http://www.AzillionRecords.blogspot.com             NaN  training   small   
4  http://www.AzillionRecords.blogspot.com             NaN  training  medium   

   bit_rate comments.2  composer       date_created.2        date_recorded  \
0     track      track     track                track                track   
1  bit_rate   comments  composer         date_created        date_recorded   
2       NaN        NaN       NaN                  NaN                  NaN   
3    256000          0       NaN  2008-11-26 01:48:12  2008-11-26 00:00:00   
4    256000          0

In [0]:
tracks = tracks.drop([0,1,2]).reset_index()

In [95]:
pd.set_option('display.max_columns', None)
tracks.head()

index  NaN comments         date_created        date_released engineer  \
0      3    2        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
1      4    3        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
2      5    5        0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3      6   10        0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
4      7   20        0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN   

  favorites id                                information listens producer  \
0         4  1                                    <p></p>    6073      NaN   
1         4  1                                    <p></p>    6073      NaN   
2         4  1                                    <p></p>    6073      NaN   
3         4  6                                        NaN   47632      NaN   
4         2  4  <p> "spiritual songs" from Nicky Cook</p>    2710      NaN   

  tags                 title tracks   type    active_year_begin  \
0   []  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
1   []  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
2   []  AWOL - A Way Of Life      7  Album  2006-01-01 00:00:00   
3   []     Constant Hitmaker      2  Album                  NaN   
4   []                 Niris     13  Album  1990-01-01 00:00:00   

       active_year_end                                  associated_labels  \
0                  NaN                                                NaN   
1                  NaN                                                NaN   
2                  NaN                                                NaN   
3                  NaN  Mexican Summer, Richie Records, Woodsist, Skul...   
4  2011-01-01 00:00:00                                                NaN   

                                                 bio comments.1  \
0  <p>A Way Of Life, A Collective of Hip-Hop from...          0   
1  <p>A Way Of Life, A Collective of Hip-Hop from...          0   
2  <p>A Way Of Life, A Collective of Hip-Hop from...          0   
3  <p><span style="font-family:Verdana, Geneva, A...          3   
4  <p>Songs written by: Nicky Cook</p>\n<p>VOCALS...          2   

        date_created.1 favorites.1 id.1    latitude            location  \
0  2008-11-26 01:42:32           9    1  40.0583238          New Jersey   
1  2008-11-26 01:42:32           9    1  40.0583238          New Jersey   
2  2008-11-26 01:42:32           9    1  40.0583238          New Jersey   
3  2008-11-26 01:42:55          74    6         NaN                 NaN   
4  2008-11-26 01:42:52          10    4   51.895927  Colchester England   

     longitude                                            members        name  \
0  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
1  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
2  -74.4056612  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
3          NaN                           Kurt Vile, the Violators   Kurt Vile   
4     0.891874                                       Nicky Cook\n  Nicky Cook   

                                    related_projects  \
0  The list of past projects is 2 long but every1...   
1  The list of past projects is 2 long but every1...   
2  The list of past projects is 2 long but every1...   
3                                                NaN   
4                                                NaN   

                                              tags.1  \
0                                           ['awol']   
1                                           ['awol']   
2                                           ['awol']   
3                            ['philly', 'kurt vile']   
4  ['instrumentals', 'experimental pop', 'post pu...   

                                   website wikipedia_page     split  subset  \
0  http://www.AzillionRecords.blogspot.com            NaN  training   small   
1  http://www.AzillionRecords.bl

In [0]:
tracks.shape

(106576, 53)

In [0]:
#appears to be most descriptive set - selected in doc notebook
#our order: album, artist, set, track
columns = [
    'title.1',
    'genres_all',
    'genre_top',
    'duration',
    'listens.1',
    'title',
    'listens',
    'tags',
    'name',
    'location',
]

df = tracks[columns]

In [0]:
df = df.rename(columns = {
    'title.1' : 'track_title',
    'listens.1':'track_listens',
    'title':'album',
    'listens':'album_listens',
    'name': 'artist'})

In [112]:
df.head()

track_title         genres_all genre_top duration track_listens  \
0             Food               [21]   Hip-Hop      168          1293   
1     Electric Ave               [21]   Hip-Hop      237           514   
2       This World               [21]   Hip-Hop      206          1151   
3          Freeway               [10]       Pop      161         50135   
4  Spiritual Level  [17, 10, 76, 103]       NaN      311           361   

                  album album_listens tags      artist            location  
0  AWOL - A Way Of Life          6073   []        AWOL          New Jersey  
1  AWOL - A Way Of Life          6073   []        AWOL          New Jersey  
2  AWOL - A Way Of Life          6073   []        AWOL          New Jersey  
3     Constant Hitmaker         47632   []   Kurt Vile                 NaN  
4                 Niris          2710   []  Nicky Cook  Colchester England

In [113]:
df.shape

(106574, 10)

In [114]:
df.isnull().sum()
#I'd like to re-engineer genre_top
#not sure why nothing appears in tags

track_title          1
genres_all           0
genre_top        56976
duration             0
track_listens        0
album             1025
album_listens        0
tags                 0
artist               0
location         36364
dtype: int64

In [0]:
df['album'] = df.album.replace({np.nan:'None'})
df['location'] = df.location.replace({np.nan:'None'})

In [0]:
#df['track_title'] = df.track_title.replace({np.nan:'None'})
df['track_title'] = df.track_title.replace({'None':'Untitled'})

In [116]:
df.dtypes #fix duration, track_listens, album_listens

track_title      object
genres_all       object
genre_top        object
duration         object
track_listens    object
album            object
album_listens    object
tags             object
artist           object
location         object
dtype: object

In [0]:
df['duration'] = df['duration'].astype(int)
df['track_listens'] = df['track_listens'].astype(int)
df['album_listens'] = df['album_listens'].astype(int)

In [125]:
df.isnull().sum()

track_title          0
genres_all           0
genre_top        56976
duration             0
track_listens        0
album                0
album_listens        0
tags                 0
artist               0
location             0
dtype: int64

In [0]:
#now that only genre_top has nan drop nans
df = df.dropna().reset_index()

In [127]:
df.describe()

index      duration  track_listens  album_listens
count   49598.000000  49598.000000   49598.000000   4.959800e+04
mean    48261.669422    268.627263    1586.328380   1.997469e+04
std     31139.382011    284.327919    6039.952955   5.736980e+04
min         0.000000      0.000000       1.000000  -1.000000e+00
25%     20734.250000    146.000000     212.000000   2.602000e+03
50%     45629.500000    211.000000     520.000000   6.092000e+03
75%     75090.750000    299.000000    1321.000000   1.621900e+04
max    106572.000000  11030.000000  543252.000000   1.193803e+06

In [130]:
df.describe(include=[np.object])

track_title genres_all genre_top              album   tags  \
count        49598      49598     49598              49598  49598   
unique       45195        726        16               7076    993   
top       Untitled       [21]      Rock  microSong Entries     []   
freq           195       2735     14182                310  40974   

              artist location  
count          49598    49598  
unique          9070     1565  
top     James Kibbie     None  
freq             319    17488

In [0]:
#I'm going to predict with topgenre for time's sake
#I'd like to convert each string feature into an int by its unique
X = df.drop(columns = ['genre_top', 'genres_all'])
y = df['genre_top']

In [148]:
#convert the strings to classification integers
n = 0
for genre in df['genre_top'].unique():
  df['genre_top'] = df['genre_top'].replace({genre:n})
  n = n+1

df['genre_top'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [0]:
n = 0
for genre in df['album'].unique():
  df['album'] = df['album'].replace({genre:n})
  n = n+1

In [0]:
n = 0
for tags in df['tags'].unique():
  df['tags'] = df['tags'].replace({tags:n})
  n = n+1

In [0]:
n = 0
for artist in df['artist'].unique():
  df['artist'] = df['artist'].replace({artist:n})
  n = n+1

In [0]:
n = 0
for location in df['location'].unique():
  df['location'] = df['location'].replace({location:n})
  n = n+1

In [154]:
#please...
df.head() #yes we can continue to the regression

index   track_title genres_all  genre_top  duration  track_listens  album  \
0      0          Food       [21]          0       168           1293      0   
1      1  Electric Ave       [21]          0       237            514      0   
2      2    This World       [21]          0       206           1151      0   
3      3       Freeway       [10]          1       161          50135      1   
4      9  Street Music       [21]          0       207            943      0   

   album_listens  tags  artist  location  
0           6073     0       0         0  
1           6073     0       0         0  
2           6073     0       0         0  
3          47632     0       1         1  
4           6073     0       0         0

In [0]:
#I'm going to predict with topgenre for time's sake
X = df.drop(columns = ['genre_top', 'genres_all', 'track_title','index'])
y = df['genre_top']

In [0]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X,y,test_size=0.2, random_state=42)

model2 = LogisticRegression(random_state=42, solver = 'lbfgs',
                           multi_class = 'multinomial', max_iter=8000)

model2.fit(Xtrain, ytrain)
model2.score(Xtest, ytest)

This is the biggest data you've played with so far, and while it does generally fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

## Resources and stretch goals

- Check out the other .csv files from the FMA dataset, and see if you can join them or otherwise fit interesting models with them
- [Logistic regression from scratch in numpy](https://blog.goodaudience.com/logistic-regression-from-scratch-in-numpy-5841c09e425f) - if you want to dig in a bit more to both the code and math (also takes a gradient descent approach, introducing the logistic loss function)
- Create a visualization to show predictions of your model - ideally show a confidence interval based on error!
- Check out and compare classification models from scikit-learn, such as [SVM](https://scikit-learn.org/stable/modules/svm.html#classification), [decision trees](https://scikit-learn.org/stable/modules/tree.html#classification), and [naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html). The underlying math will vary significantly, but the API (how you write the code) and interpretation will actually be fairly similar.
- Sign up for [Kaggle](https://kaggle.com), and find a competition to try logistic regression with
- (Not logistic regression related) If you enjoyed the assignment, you may want to read up on [music informatics](https://en.wikipedia.org/wiki/Music_informatics), which is how those audio features were actually calculated. The FMA includes the actual raw audio, so (while this is more of a longterm project than a stretch goal, and won't fit in Colab) if you'd like you can check those out and see what sort of deeper analysis you can do.