# Lambda School Data Science - Logistic Regression

Logistic regression is the baseline for classification models, as well as a handy way to predict probabilities (since those too live in the unit interval). While relatively simple, it is also the foundation for more sophisticated classification techniques such as neural networks (many of which can effectively be thought of as networks of logistic models).

## Lecture - Where Linear goes Wrong
### Return of the Titanic 🚢

You've likely already explored the rich dataset that is the Titanic - let's use regression and try to predict survival with it. The data is [available from Kaggle](https://www.kaggle.com/c/titanic/data), so we'll also play a bit with [the Kaggle API](https://github.com/Kaggle/kaggle-api).

In [4]:
!pip install kaggle

    100% |████████████████████████████████| 61kB 768kB/s ta 0:00:01
    100% |████████████████████████████████| 133kB 2.1MB/s ta 0:00:01
    100% |████████████████████████████████| 245kB 2.4MB/s ta 0:00:011
  Running setup.py bdist_wheel for kaggle ... done
  Stored in directory: /Users/ksmith/Library/Caches/pip/wheels/5a/2d/0c/9fc539e558586b9ed9127916a7f4e620163c24cc97460b1188
  Running setup.py bdist_wheel for python-slugify ... done
  Stored in directory: /Users/ksmith/Library/Caches/pip/wheels/2b/9e/c8/14a18ab55d8f144384de8186a3df8401dcc9264936f71d470f
Successfully built kaggle python-slugify
  Found existing installation: urllib3 1.23
    Uninstalling urllib3-1.23:
      Successfully uninstalled urllib3-1.23
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [7]:
# Note - you'll also have to sign up for Kaggle and authorize the API
# https://github.com/Kaggle/kaggle-api#api-credentials

# This essentially means uploading a kaggle.json file
# For Colab we can have it in Google Drive
from google.colab import drive
drive.mount('/content/drive')
%env KAGGLE_CONFIG_DIR=/content/drive/My Drive/

# You also have to join the Titanic competition to have access to the data
!kaggle competitions download -c titanic

ModuleNotFoundError: No module named 'google'

In [9]:
# How would we try to do this with linear regression?
import pandas as pd

train_df = pd.read_csv('train.csv').dropna()
test_df = pd.read_csv('test.csv').dropna()  # Unlabeled, for Kaggle submission

train_df.head()

FileNotFoundError: File b'train.csv' does not exist

In [4]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [5]:
from sklearn.linear_model import LinearRegression

X = train_df[['Pclass', 'Age', 'Fare']]
y = train_df.Survived

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.08389810726550917

In [6]:
linear_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([0.79543117, 0.58610823, 0.67595121, 0.793829  , 0.62090522,
       0.72542107, 0.59848968, 0.58734245, 0.48567063, 0.77627736,
       0.84211887, 0.57052439, 0.7754689 , 0.96621114, 0.70287941,
       0.57673837, 0.72321391, 0.75894755, 0.77968041, 0.50246003,
       0.49858077, 0.7474959 , 0.3542282 , 0.61648435, 0.71300224,
       0.66294608, 0.53175333, 0.77397395, 0.68419387, 0.68395536,
       0.52041202, 0.56814038, 0.79586606, 0.81372012, 0.61068545,
       0.57260627, 0.52525981, 0.58055388, 0.45584728, 0.67976208,
       0.8226707 , 0.84286197, 0.96189157, 0.66724612, 0.68589478,
       0.61846513, 0.63455044, 0.68275686, 0.65738372, 0.45198998,
       0.59988596, 0.63845908, 0.63132487, 0.7888473 , 0.60126246,
       0.79714045, 0.78713803, 0.54643775, 0.42823635, 0.7711724 ,
       0.53552976, 0.55608044, 0.54480459, 0.57031915, 0.65080369,
       0.77958926, 0.6371013 , 0.70993488, 0.71493598, 0.60375943,
       0.54407206, 0.48186138, 0.76576089, 0.75456305, 0.53968

In [7]:
linear_reg.coef_

array([-0.08596295, -0.00829314,  0.00048775])

In [8]:
import numpy as np

test_case = np.array([[1, 5, 500]])  # Rich 5-year old in first class
linear_reg.predict(test_case)

array([1.14845883])

In [9]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression().fit(X, y)
log_reg.score(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7103825136612022

In [10]:
log_reg.predict(test_df[['Pclass', 'Age', 'Fare']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
log_reg.predict(test_case)[0]

1

In [12]:
help(log_reg.predict)

Help on method predict in module sklearn.linear_model.base:

predict(X) method of sklearn.linear_model.logistic.LogisticRegression instance
    Predict class labels for samples in X.
    
    Parameters
    ----------
    X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
    
    Returns
    -------
    C : array, shape [n_samples]
        Predicted class label per sample.



In [13]:
log_reg.predict_proba(test_case)[0]

array([0.02485552, 0.97514448])

In [14]:
# What's the math?
log_reg.coef_

array([[-0.0455017 , -0.02912513,  0.0048037 ]])

In [15]:
log_reg.intercept_

array([1.45878264])

In [0]:
# The logistic sigmoid "squishing" function, implemented to accept numpy arrays
def sigmoid(x):
  return 1 / (1 + np.e**(-x))

In [17]:
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.97514448]])

So, clearly a more appropriate model in this situation! For more on the math, [see this Wikipedia example](https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study).

For live - let's tackle [another classification dataset on absenteeism](http://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work) - it has 21 classes, but remember, scikit-learn LogisticRegression automatically handles more than two classes. How? By essentially treating each label as different (1) from some base class (0).

In [0]:
# Live - let's try absenteeism!

## Assignment - real-world classification

We're going to check out a larger dataset - the [FMA Free Music Archive data](https://github.com/mdeff/fma). It has a selection of CSVs with metadata and calculated audio features that you can load and try to use to classify genre of tracks. To get you started:

In [17]:
from shutil import unpack_archive
unpack_archive('fma_metadata.zip', '/Users/ksmith/Documents/Code/DS1/Unit2/DS-Unit-2-Sprint-3-Advanced-Regression/module1-logistic-regression')

In [96]:
tracks = pd.read_csv('/Users/ksmith/Documents/Code/DS1/Unit2/DS-Unit-2-Sprint-3-Advanced-Regression/module1-logistic-regression/fma_metadata/tracks.csv', low_memory=False,header=1)

In [97]:
tracks.head()

Unnamed: 0  comments         date_created        date_released engineer  \
0   track_id       NaN                  NaN                  NaN      NaN   
1          2       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
2          3       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3          5       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4         10       0.0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   

   favorites   id information  listens producer tags                 title  \
0        NaN  NaN         NaN      NaN      NaN  NaN                   NaN   
1        4.0  1.0     <p></p>   6073.0      NaN   []  AWOL - A Way Of Life   
2        4.0  1.0     <p></p>   6073.0      NaN   []  AWOL - A Way Of Life   
3        4.0  1.0     <p></p>   6073.0      NaN   []  AWOL - A Way Of Life   
4        4.0  6.0         NaN  47632.0      NaN   []     Constant Hitmaker   

   tracks   type    active_year_begin active_year_end  \
0     NaN    NaN                  NaN             NaN   
1     7.0  Album  2006-01-01 00:00:00             NaN   
2     7.0  Album  2006-01-01 00:00:00             NaN   
3     7.0  Album  2006-01-01 00:00:00             NaN   
4     2.0  Album                  NaN             NaN   

                                   associated_labels  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4  Mexican Summer, Richie Records, Woodsist, Skul...   

                                                 bio  comments.1  \
0                                                NaN         NaN   
1  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
4  <p><span style="font-family:Verdana, Geneva, A...         3.0   

        date_created.1  favorites.1  id.1   latitude    location  longitude  \
0                  NaN          NaN   NaN        NaN         NaN        NaN   
1  2008-11-26 01:42:32          9.0   1.0  40.058324  New Jersey -74.405661   
2  2008-11-26 01:42:32          9.0   1.0  40.058324  New Jersey -74.405661   
3  2008-11-26 01:42:32          9.0   1.0  40.058324  New Jersey -74.405661   
4  2008-11-26 01:42:55         74.0   6.0        NaN         NaN        NaN   

                                             members       name  \
0                                                NaN        NaN   
1  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
2  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
3  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...       AWOL   
4                           Kurt Vile, the Violators  Kurt Vile   

                                    related_projects                   tags.1  \
0                                                NaN                      NaN   
1  The list of past projects is 2 long but every1...                 ['awol']   
2  The list of past projects is 2 long but every1...                 ['awol']   
3  The list of past projects is 2 long but every1...                 ['awol']   
4                                                NaN  ['philly', 'kurt vile']   

                                   website wikipedia_page     split  subset  \
0                                      NaN            NaN       NaN     NaN   
1  http://www.AzillionRecords.blogspot.com            NaN  training   small   
2  http://www.AzillionRecords.blogspot.com            NaN  training  medium   
3  http://www.AzillionRecords.blogspot.com            NaN  training   small   
4                      http://kurtvile.com            NaN  training   small   

   bit_rate  comments.2   composer       date_created.2        date_recorded  \
0       NaN         NaN        NaN                  NaN      

In [98]:
tracks.drop(index=0, inplace=True)
tracks.rename(index=str, columns={'Unnamed: 0': 'track_id'}, inplace=True)
tracks.head()

track_id  comments         date_created        date_released engineer  \
1        2       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
2        3       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3        5       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4       10       0.0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
5       20       0.0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN   

   favorites   id                                information  listens  \
1        4.0  1.0                                    <p></p>   6073.0   
2        4.0  1.0                                    <p></p>   6073.0   
3        4.0  1.0                                    <p></p>   6073.0   
4        4.0  6.0                                        NaN  47632.0   
5        2.0  4.0  <p> "spiritual songs" from Nicky Cook</p>   2710.0   

  producer tags                 title  tracks   type    active_year_begin  \
1      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
2      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
3      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
4      NaN   []     Constant Hitmaker     2.0  Album                  NaN   
5      NaN   []                 Niris    13.0  Album  1990-01-01 00:00:00   

       active_year_end                                  associated_labels  \
1                  NaN                                                NaN   
2                  NaN                                                NaN   
3                  NaN                                                NaN   
4                  NaN  Mexican Summer, Richie Records, Woodsist, Skul...   
5  2011-01-01 00:00:00                                                NaN   

                                                 bio  comments.1  \
1  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
4  <p><span style="font-family:Verdana, Geneva, A...         3.0   
5  <p>Songs written by: Nicky Cook</p>\n<p>VOCALS...         2.0   

        date_created.1  favorites.1  id.1   latitude            location  \
1  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
2  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
3  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
4  2008-11-26 01:42:55         74.0   6.0        NaN                 NaN   
5  2008-11-26 01:42:52         10.0   4.0  51.895927  Colchester England   

   longitude                                            members        name  \
1 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
2 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
3 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
4        NaN                           Kurt Vile, the Violators   Kurt Vile   
5   0.891874                                       Nicky Cook\n  Nicky Cook   

                                    related_projects  \
1  The list of past projects is 2 long but every1...   
2  The list of past projects is 2 long but every1...   
3  The list of past projects is 2 long but every1...   
4                                                NaN   
5                                                NaN   

                                              tags.1  \
1                                           ['awol']   
2                                           ['awol']   
3                                           ['awol']   
4                            ['philly', 'kurt vile']   
5  ['instrumentals', 'experimental pop', 'post pu...   

                                   website wikipedia_page     split  subset  \
1  http://www.AzillionRecords.blogspot.com            NaN  training   small   
2  http://www

In [99]:
tracks.describe()

comments      favorites             id       listens  \
count  106574.000000  106574.000000  106574.000000  1.065740e+05   
mean        0.394946       1.286927   12826.933914  3.212031e+04   
std         2.268915       3.133035    6290.261805  1.478532e+05   
min        -1.000000      -1.000000      -1.000000 -1.000000e+00   
25%         0.000000       0.000000    7793.000000  3.361000e+03   
50%         0.000000       0.000000   13374.000000  8.982000e+03   
75%         0.000000       1.000000   18203.000000  2.363500e+04   
max        53.000000      61.000000   22940.000000  3.564243e+06   

              tracks     comments.1    favorites.1           id.1  \
count  106574.000000  106574.000000  106574.000000  106574.000000   
mean       19.721452       1.894702      30.041915   12036.770404   
std        39.943673       6.297679     100.511408    6881.420867   
min        -1.000000      -1.000000      -1.000000       1.000000   
25%         7.000000       0.000000       1.000000    6443.000000   
50%        11.000000       0.000000       5.000000   12029.500000   
75%        17.000000       1.000000      16.000000   18011.000000   
max       652.000000      79.000000     963.000000   24357.000000   

           latitude     longitude       bit_rate     comments.2  \
count  44544.000000  44544.000000  106574.000000  106574.000000   
mean      39.901626    -38.668642  263274.695048       0.031621   
std       18.240860     65.237220   67623.443584       0.321993   
min      -45.878760   -157.526855      -1.000000       0.000000   
25%       39.271398    -79.997459  192000.000000       0.000000   
50%       41.387917    -73.554431  299914.000000       0.000000   
75%       48.856930      4.351710  320000.000000       0.000000   
max       67.286005    175.277000  448000.000000      37.000000   

            duration    favorites.2      interest      listens.1  \
count  106574.000000  106574.000000  1.065740e+05  106574.000000   
mean      277.849100       3.182521  3.541310e+03    2329.353548   
std       305.518553      13.513820  1.901743e+04    8028.070647   
min         0.000000       0.000000  2.000000e+00       0.000000   
25%       149.000000       0.000000  5.990000e+02     292.000000   
50%       216.000000       1.000000  1.314000e+03     764.000000   
75%       305.000000       3.000000  3.059000e+03    2018.000000   
max     18350.000000    1482.000000  3.293557e+06  543252.000000   

              number  
count  106574.000000  
mean        8.260945  
std        15.243271  
min         0.000000  
25%         2.000000  
50%         5.000000  
75%         9.000000  
max       255.000000

In [100]:
pd.set_option('display.max_columns', None)  # Unlimited columns
tracks.head()

track_id  comments         date_created        date_released engineer  \
1        2       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
2        3       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
3        5       0.0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN   
4       10       0.0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN   
5       20       0.0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN   

   favorites   id                                information  listens  \
1        4.0  1.0                                    <p></p>   6073.0   
2        4.0  1.0                                    <p></p>   6073.0   
3        4.0  1.0                                    <p></p>   6073.0   
4        4.0  6.0                                        NaN  47632.0   
5        2.0  4.0  <p> "spiritual songs" from Nicky Cook</p>   2710.0   

  producer tags                 title  tracks   type    active_year_begin  \
1      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
2      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
3      NaN   []  AWOL - A Way Of Life     7.0  Album  2006-01-01 00:00:00   
4      NaN   []     Constant Hitmaker     2.0  Album                  NaN   
5      NaN   []                 Niris    13.0  Album  1990-01-01 00:00:00   

       active_year_end                                  associated_labels  \
1                  NaN                                                NaN   
2                  NaN                                                NaN   
3                  NaN                                                NaN   
4                  NaN  Mexican Summer, Richie Records, Woodsist, Skul...   
5  2011-01-01 00:00:00                                                NaN   

                                                 bio  comments.1  \
1  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
2  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
3  <p>A Way Of Life, A Collective of Hip-Hop from...         0.0   
4  <p><span style="font-family:Verdana, Geneva, A...         3.0   
5  <p>Songs written by: Nicky Cook</p>\n<p>VOCALS...         2.0   

        date_created.1  favorites.1  id.1   latitude            location  \
1  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
2  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
3  2008-11-26 01:42:32          9.0   1.0  40.058324          New Jersey   
4  2008-11-26 01:42:55         74.0   6.0        NaN                 NaN   
5  2008-11-26 01:42:52         10.0   4.0  51.895927  Colchester England   

   longitude                                            members        name  \
1 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
2 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
3 -74.405661  Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...        AWOL   
4        NaN                           Kurt Vile, the Violators   Kurt Vile   
5   0.891874                                       Nicky Cook\n  Nicky Cook   

                                    related_projects  \
1  The list of past projects is 2 long but every1...   
2  The list of past projects is 2 long but every1...   
3  The list of past projects is 2 long but every1...   
4                                                NaN   
5                                                NaN   

                                              tags.1  \
1                                           ['awol']   
2                                           ['awol']   
3                                           ['awol']   
4                            ['philly', 'kurt vile']   
5  ['instrumentals', 'experimental pop', 'post pu...   

                                   website wikipedia_page     split  subset  \
1  http://www.AzillionRecords.blogspot.com            NaN  training   small   
2  http://www

In [102]:
#genre_top is what we want to determine
#Need to update it to an int

tracks['genre_top'].unique()

array(['Hip-Hop', 'Pop', nan, 'Rock', 'Experimental', 'Folk', 'Jazz',
       'Electronic', 'Spoken', 'International', 'Soul-RnB', 'Blues',
       'Country', 'Classical', 'Old-Time / Historic', 'Instrumental',
       'Easy Listening'], dtype=object)

In [103]:
di = {'Hip-Hop':1, 'Pop':2, 'Rock':3, 'Experimental':4, 'Folk':5, 'Jazz':6,
       'Electronic':7, 'Spoken':8, 'International':9, 'Soul-RnB':10, 'Blues':11,
       'Country':12, 'Classical':13, 'Old-Time / Historic':14, 'Instrumental':15,
       'Easy Listening':16}

tracks['genre_top'].replace(di, inplace=True)

In [104]:
tracks = tracks.select_dtypes('number')
tracks.head()

comments  favorites   id  listens  tracks  comments.1  favorites.1  id.1  \
1       0.0        4.0  1.0   6073.0     7.0         0.0          9.0   1.0   
2       0.0        4.0  1.0   6073.0     7.0         0.0          9.0   1.0   
3       0.0        4.0  1.0   6073.0     7.0         0.0          9.0   1.0   
4       0.0        4.0  6.0  47632.0     2.0         3.0         74.0   6.0   
5       0.0        2.0  4.0   2710.0    13.0         2.0         10.0   4.0   

    latitude  longitude  bit_rate  comments.2  duration  favorites.2  \
1  40.058324 -74.405661  256000.0         0.0     168.0          2.0   
2  40.058324 -74.405661  256000.0         0.0     237.0          1.0   
3  40.058324 -74.405661  256000.0         0.0     206.0          6.0   
4        NaN        NaN  192000.0         0.0     161.0        178.0   
5  51.895927   0.891874  256000.0         0.0     311.0          0.0   

   genre_top  interest  listens.1  number  
1        1.0    4656.0     1293.0     3.0  
2        1.0    1470.0      514.0     4.0  
3        1.0    1933.0     1151.0     6.0  
4        2.0   54881.0    50135.0     1.0  
5        NaN     978.0      361.0     3.0

In [105]:
tracks.isna().sum()

comments           0
favorites          0
id                 0
listens            0
tracks             0
comments.1         0
favorites.1        0
id.1               0
latitude       62030
longitude      62030
bit_rate           0
comments.2         0
duration           0
favorites.2        0
genre_top      56976
interest           0
listens.1          0
number             0
dtype: int64

In [106]:
import numpy as np

new_df = tracks[np.isfinite(tracks['genre_top'])]
new_df.isna().sum()

comments           0
favorites          0
id                 0
listens            0
tracks             0
comments.1         0
favorites.1        0
id.1               0
latitude       28618
longitude      28618
bit_rate           0
comments.2         0
duration           0
favorites.2        0
genre_top          0
interest           0
listens.1          0
number             0
dtype: int64

In [108]:
print(new_df['latitude'].mean())
print(new_df['latitude'].mode())
print(new_df['longitude'].mean())
print(new_df['longitude'].mode())

39.62460890050608
0    40.65
dtype: float64
-47.30599397936924
0   -73.95
dtype: float64


In [109]:
new_df['latitude'].fillna(new_df['latitude'].mean, inplace=True)
new_df['longitude'].fillna(new_df['longitude'].mean, inplace=True)

new_df.isna().sum()

/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5434: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


comments       0
favorites      0
id             0
listens        0
tracks         0
comments.1     0
favorites.1    0
id.1           0
latitude       0
longitude      0
bit_rate       0
comments.2     0
duration       0
favorites.2    0
genre_top      0
interest       0
listens.1      0
number         0
dtype: int64

In [111]:
from sklearn.linear_model import LogisticRegression

X = new_df.drop('genre_top', axis = 1)
y = new_df['genre_top']

tracks_log1 = LogisticRegression().fit(X, y)
tracks_log1.score(X, y)

TypeError: float() argument must be a string or a number, not 'method'

In [112]:
print(X)

RecursionError: maximum recursion depth exceeded while calling a Python object

This is the biggest data you've played with so far, and while it does generally fit in Colab, it can take awhile to run. That's part of the challenge!

Your tasks:
- Clean up the variable names in the dataframe
- Use logistic regression to fit a model predicting (primary/top) genre
- Inspect, iterate, and improve your model
- Answer the following questions (written, ~paragraph each):
  - What are the best predictors of genre?
  - What information isn't very useful for predicting genre?
  - What surprised you the most about your results?

*Important caveats*:
- This is going to be difficult data to work with - don't let the perfect be the enemy of the good!
- Be creative in cleaning it up - if the best way you know how to do it is download it locally and edit as a spreadsheet, that's OK!
- If the data size becomes problematic, consider sampling/subsetting
- You do not need perfect or complete results - just something plausible that runs, and that supports the reasoning in your written answers

If you find that fitting a model to classify *all* genres isn't very good, it's totally OK to limit to the most frequent genres, or perhaps trying to combine or cluster genres as a preprocessing step. Even then, there will be limits to how good a model can be with just this metadata - if you really want to train an effective genre classifier, you'll have to involve the other data (see stretch goals).

This is real data - there is no "one correct answer", so you can take this in a variety of directions. Just make sure to support your findings, and feel free to share them as well! This is meant to be practice for dealing with other "messy" data, a common task in data science.

## Resources and stretch goals

- Check out the other .csv files from the FMA dataset, and see if you can join them or otherwise fit interesting models with them
- [Logistic regression from scratch in numpy](https://blog.goodaudience.com/logistic-regression-from-scratch-in-numpy-5841c09e425f) - if you want to dig in a bit more to both the code and math (also takes a gradient descent approach, introducing the logistic loss function)
- Create a visualization to show predictions of your model - ideally show a confidence interval based on error!
- Check out and compare classification models from scikit-learn, such as [SVM](https://scikit-learn.org/stable/modules/svm.html#classification), [decision trees](https://scikit-learn.org/stable/modules/tree.html#classification), and [naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html). The underlying math will vary significantly, but the API (how you write the code) and interpretation will actually be fairly similar.
- Sign up for [Kaggle](https://kaggle.com), and find a competition to try logistic regression with
- (Not logistic regression related) If you enjoyed the assignment, you may want to read up on [music informatics](https://en.wikipedia.org/wiki/Music_informatics), which is how those audio features were actually calculated. The FMA includes the actual raw audio, so (while this is more of a longterm project than a stretch goal, and won't fit in Colab) if you'd like you can check those out and see what sort of deeper analysis you can do.